Repository stellio-hub/stellio-context-broker, pull requests merged in 2020-06, with the labels that each got.

#54 Fix/53 fix http client dependency conflicts
  entity-service/build.gradle.kts
  entity-service/src/main/kotlin/com/egm/stellio/entity/config/DataSourceConfiguration.kt
  entity-service/src/main/resources/application-docker.properties
  entity-service/src/main/resources/application.properties
  entity-service/src/main/resources/db/liquigraph/changelog.xml
  entity-service/src/main/resources/neo4j/migrations/V01__fix_temporal_values_data_type.cypher
Labels: entity, fix

#50 feat(entity) add support for entityOperation/upsert with update option #21
  build.gradle.kts
  entity-service/src/main/kotlin/com/egm/stellio/entity/service/EntityOperationService.kt
  entity-service/src/main/kotlin/com/egm/stellio/entity/service/EntityService.kt
  entity-service/src/main/kotlin/com/egm/stellio/entity/service/RepositoryEventsListener.kt
  entity-service/src/main/kotlin/com/egm/stellio/entity/web/APIResponses.kt
  entity-service/src/main/kotlin/com/egm/stellio/entity/web/EntityOperationHandler.kt
  entity-service/src/test/kotlin/com/egm/stellio/entity/service/EntityOperationServiceTests.kt
  entity-service/src/test/kotlin/com/egm/stellio/entity/web/EntityOperationHandlerTests.kt
  entity-service/src/test/resources/ngsild/hcmr/HCMR_test_file_invalid_relation_update.json
  search-service/src/main/kotlin/com/egm/stellio/search/service/TemporalEntityAttributeService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/web/TemporalEntityHandler.kt
  search-service/src/test/kotlin/com/egm/stellio/search/service/TemporalEntityAttributeServiceTests.kt
  shared/src/main/kotlin/com/egm/stellio/shared/model/ExpandedEntity.kt
  shared/src/main/kotlin/com/egm/stellio/shared/util/NgsiLdParsingUtils.kt
Labels: feature

#67 Fix/64 fix temporal values injection
  search-service/src/main/kotlin/com/egm/stellio/search/service/TemporalEntityAttributeService.kt
  search-service/src/test/kotlin/com/egm/stellio/search/service/TemporalEntityAttributeServiceTests.kt
Labels: fix

#72 feat: set default conf for actuator endpoints
  build.gradle.kts
  entity-service/src/main/kotlin/com/egm/stellio/entity/config/WebSecurityConfig.kt
  entity-service/src/main/resources/application.properties
  search-service/src/main/kotlin/com/egm/stellio/search/config/WebSecurityConfig.kt
  search-service/src/main/resources/application.properties
  subscription-service/src/main/kotlin/com/egm/stellio/subscription/config/WebSecurityConfig.kt
  subscription-service/src/main/resources/application.properties
Labels: feature

#68 Documentation/57 add quickguide
  API_Quick_Start.md
  README.md
  samples/apiary.jsonld
  samples/apiculture_entities.jsonld
  samples/beehive.jsonld
  samples/beehive_addName.jsonld
  samples/beehive_secondTemperatureUpdate.jsonld
  samples/beehive_updateHumidity.jsonld
  samples/beehive_updateTemperature.jsonld
  samples/beekeeper.jsonld
  samples/sensor_humidity.jsonld
  samples/sensor_temperature.jsonld
  samples/subscription_newEndpoint.jsonld
  samples/subscription_newQuery.jsonld
  samples/subscription_to_beehive.jsonld
Labels: documentation

#58 feat(entity): upgrade to Neo4j 4.0 + update cypher queries syntax #37
  .env
  docker-compose.yml
  entity-service/.env
  entity-service/docker-compose.yml
  entity-service/src/main/kotlin/com/egm/stellio/entity/config/Neo4jConfiguration.kt
  entity-service/src/main/kotlin/com/egm/stellio/entity/repository/EntityRepository.kt
  entity-service/src/main/kotlin/com/egm/stellio/entity/repository/Neo4jRepository.kt
  entity-service/src/test/kotlin/com/egm/stellio/entity/config/TestContainersConfiguration.kt
Labels: feature

#74 feat: use message from the initial exception when available #41 #65
  entity-service/src/test/kotlin/com/egm/stellio/entity/web/EntityHandlerTests.kt
  shared/src/main/kotlin/com/egm/stellio/shared/web/ExceptionHandler.kt
Labels: feature

#77 fix(entity): configure jib to synchronize launch of entity service an…
  entity-service/build.gradle.kts
  entity-service/src/main/jib/database/wait-for-neo4j.sh
Labels: entity, fix

#80 fix(entity): set wait_for_neo4j.sh timeout as variable with a default value 100
  entity-service/build.gradle.kts
Labels: entity, fix

#75 feat(entity): improve queries in entity creation process #70
  entity-service/src/main/kotlin/com/egm/stellio/entity/model/Attribute.kt
  entity-service/src/main/kotlin/com/egm/stellio/entity/model/Property.kt
  entity-service/src/main/kotlin/com/egm/stellio/entity/repository/AttributeRepository.kt
  entity-service/src/main/kotlin/com/egm/stellio/entity/repository/EntityRepository.kt
  entity-service/src/main/kotlin/com/egm/stellio/entity/repository/Neo4jRepository.kt
  entity-service/src/main/kotlin/com/egm/stellio/entity/service/EntityService.kt
  entity-service/src/main/kotlin/com/egm/stellio/entity/web/EntityHandler.kt
  entity-service/src/main/resources/logback-spring.xml
  entity-service/src/main/resources/neo4j/migrations/V02__create_minimal_indexes.cypher
  entity-service/src/test/kotlin/com/egm/stellio/entity/repository/Neo4jRepositoryTests.kt
  entity-service/src/test/kotlin/com/egm/stellio/entity/service/EntityServiceTests.kt
  entity-service/src/test/kotlin/com/egm/stellio/entity/web/EntityHandlerTests.kt
  shared/src/main/kotlin/com/egm/stellio/shared/model/ExpandedEntity.kt
  shared/src/main/kotlin/com/egm/stellio/shared/util/NgsiLdParsingUtils.kt
Labels: feature

#88 fix(search): extend size of stellio_search db columns #84
  search-service/src/main/resources/db/migration/V0_9__extend_size_type_attribute_name_attribute_value_type_columns.sql
Labels: fix

#86 feat(gateway): use environment variables to load routes uri #83
  api-gateway/src/main/kotlin/com/egm/stellio/apigateway/ApiGatewayApplication.kt
Labels: feature, gateway

#90 feat(entity): upgrade neo4j migrations to 0.0.12 #89
  entity-service/build.gradle.kts
Labels: entity, feature

#92 feat(search): update temporal_entity_attribute/payload on UPDATE event #91
  search-service/src/main/kotlin/com/egm/stellio/search/listener/EntityListener.kt
  search-service/src/main/kotlin/com/egm/stellio/search/service/TemporalEntityAttributeService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/web/TemporalEntityHandler.kt
  search-service/src/test/kotlin/com/egm/stellio/search/listener/EntityListenerTest.kt
  search-service/src/test/kotlin/com/egm/stellio/search/web/TemporalEntityHandlerTests.kt
Labels: feature
