Repository stellio-hub/stellio-context-broker, pull requests merged in 2020-05, with the labels that each got.

#6 feat: case insensitive search of a sensor / device by vendorId #5
  entity-service/src/main/kotlin/com/egm/stellio/entity/repository/Neo4jRepository.kt
  entity-service/src/test/kotlin/com/egm/stellio/entity/repository/Neo4jRepositoryTests.kt
Labels: fix

#8 refactor: add a wrapper class for the representation of an expanded entity #7
  entity-service/src/main/kotlin/com/egm/stellio/entity/service/Neo4jService.kt
  entity-service/src/main/kotlin/com/egm/stellio/entity/service/RepositoryEventsListener.kt
  entity-service/src/main/kotlin/com/egm/stellio/entity/util/ParsingUtils.kt
  entity-service/src/main/kotlin/com/egm/stellio/entity/util/ValidationUtils.kt
  entity-service/src/main/kotlin/com/egm/stellio/entity/web/EntityHandler.kt
  entity-service/src/test/kotlin/com/egm/stellio/entity/service/Neo4jServiceTests.kt
  entity-service/src/test/kotlin/com/egm/stellio/entity/web/EntityHandlerTests.kt
  search-service/src/main/kotlin/com/egm/stellio/search/listener/EntityListener.kt
  search-service/src/main/kotlin/com/egm/stellio/search/service/EntityService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/service/TemporalEntityAttributeService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/web/TemporalEntityHandler.kt
  search-service/src/test/kotlin/com/egm/stellio/search/service/EntityServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/service/TemporalEntityAttributeServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/web/TemporalEntityHandlerTests.kt
  shared/src/main/kotlin/com/egm/stellio/shared/model/ExpandedEntity.kt
  shared/src/main/kotlin/com/egm/stellio/shared/util/NgsiLdParsingUtils.kt
  shared/src/main/kotlin/com/egm/stellio/shared/util/TestUtils.kt
  subscription-service/src/main/kotlin/com/egm/stellio/subscription/service/NotificationService.kt
Labels: feature

#13 Refactor/10 improve entity handling process and validation
  entity-service/src/main/kotlin/com/egm/stellio/entity/service/EntitiesListener.kt
  entity-service/src/main/kotlin/com/egm/stellio/entity/service/EntityService.kt
  entity-service/src/main/kotlin/com/egm/stellio/entity/service/RepositoryEventsListener.kt
  entity-service/src/main/kotlin/com/egm/stellio/entity/service/SubscriptionListener.kt
  entity-service/src/main/kotlin/com/egm/stellio/entity/util/ValidationUtils.kt
  entity-service/src/main/kotlin/com/egm/stellio/entity/web/EntityHandler.kt
  entity-service/src/main/kotlin/com/egm/stellio/entity/web/EntityOperationHandler.kt
  entity-service/src/test/kotlin/com/egm/stellio/entity/service/EntitiesListenerTests.kt
  entity-service/src/test/kotlin/com/egm/stellio/entity/service/EntityServiceTests.kt
  entity-service/src/test/kotlin/com/egm/stellio/entity/service/SubscriptionListenerTests.kt
  entity-service/src/test/kotlin/com/egm/stellio/entity/web/EntityHandlerTests.kt
  entity-service/src/test/kotlin/com/egm/stellio/entity/web/EntityOperationHandlerTests.kt
  search-service/src/main/kotlin/com/egm/stellio/search/web/TemporalEntityHandler.kt
  search-service/src/test/kotlin/com/egm/stellio/search/service/EntityServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/web/TemporalEntityHandlerTests.kt
  shared/src/main/kotlin/com/egm/stellio/shared/model/ExpandedEntity.kt
  shared/src/main/kotlin/com/egm/stellio/shared/util/NgsiLdParsingUtils.kt
  shared/src/test/kotlin/com/egm/stellio/shared/util/NgsiLdParsingUtilsTests.kt
  subscription-service/src/main/kotlin/com/egm/stellio/subscription/service/NotificationService.kt
Labels: chore

#9 Feature/4 implement common rules related to error types
  entity-service/src/main/kotlin/com/egm/stellio/entity/web/EntityHandler.kt
  entity-service/src/main/kotlin/com/egm/stellio/entity/web/EntityOperationHandler.kt
  entity-service/src/main/kotlin/com/egm/stellio/entity/web/Routes.kt
  entity-service/src/test/kotlin/com/egm/stellio/entity/web/EntityHandlerTests.kt
  entity-service/src/test/kotlin/com/egm/stellio/entity/web/EntityOperationHandlerTests.kt
  search-service/src/main/kotlin/com/egm/stellio/search/web/TemporalEntityHandler.kt
  search-service/src/test/kotlin/com/egm/stellio/search/web/TemporalEntityHandlerTests.kt
  shared/src/main/kotlin/com/egm/stellio/shared/model/APiExceptions.kt
  shared/src/main/kotlin/com/egm/stellio/shared/model/ErrorResponse.kt
  shared/src/main/kotlin/com/egm/stellio/shared/util/ApiUtils.kt
  shared/src/main/kotlin/com/egm/stellio/shared/util/NgsiLdParsingUtils.kt
  subscription-service/src/main/kotlin/com/egm/stellio/subscription/web/Routes.kt
  subscription-service/src/main/kotlin/com/egm/stellio/subscription/web/SubscriptionHandler.kt
  subscription-service/src/test/kotlin/com/egm/stellio/subscription/web/SubscriptionHandlerTests.kt
Labels: feature

#15 fix: accept Mime Type with parameters + return a bad request when a J…
  entity-service/src/test/kotlin/com/egm/stellio/entity/web/EntityHandlerTests.kt
  shared/src/main/kotlin/com/egm/stellio/shared/model/ErrorResponse.kt
  shared/src/main/kotlin/com/egm/stellio/shared/util/ApiUtils.kt
Labels: fix

#17 Feature/16 setup testcontainers in entity service
  build.gradle.kts
  entity-service/build.gradle.kts
  entity-service/docker-compose.yml
  entity-service/src/test/kotlin/com/egm/stellio/entity/Neo4jEmbeddedConfiguration.kt
  entity-service/src/test/kotlin/com/egm/stellio/entity/TestContainersConfiguration.kt
  entity-service/src/test/resources/ogm.properties
  search-service/build.gradle.kts
Labels: feature

#24 fix: load when needed TestContainersConfiguration & fix broken test a…
  entity-service/src/test/kotlin/com/egm/stellio/entity/TestContainersConfiguration.kt
  entity-service/src/test/kotlin/com/egm/stellio/entity/repository/EntityRepositoryTests.kt
  entity-service/src/test/kotlin/com/egm/stellio/entity/repository/Neo4jRepositoryTests.kt
  entity-service/src/test/kotlin/com/egm/stellio/entity/web/EntityOperationHandlerTests.kt
Labels: fix

#3 Fix/1 fix temporal properties data type
  entity-service/build.gradle.kts
  entity-service/src/main/kotlin/com/egm/stellio/entity/config/DataSourceConfiguration.kt
  entity-service/src/main/kotlin/com/egm/stellio/entity/model/Attribute.kt
  entity-service/src/main/kotlin/com/egm/stellio/entity/model/Entity.kt
  entity-service/src/main/kotlin/com/egm/stellio/entity/model/Property.kt
  entity-service/src/main/kotlin/com/egm/stellio/entity/model/Relationship.kt
  entity-service/src/main/kotlin/com/egm/stellio/entity/repository/Neo4jRepository.kt
  entity-service/src/main/resources/db/liquigraph/changelog.xml
  entity-service/src/test/kotlin/com/egm/stellio/entity/repository/Neo4jRepositoryTests.kt
  entity-service/src/test/kotlin/com/egm/stellio/entity/service/EntitiesListenerTests.kt
  entity-service/src/test/kotlin/com/egm/stellio/entity/service/EntityServiceTests.kt
  entity-service/src/test/kotlin/com/egm/stellio/entity/web/EntityHandlerTests.kt
  entity-service/src/test/resources/mock/response_entities_by_label.json
  entity-service/src/test/resources/mock/response_entities_by_label_and_query.json
  entity-service/src/test/resources/ngsild/HCMR.json
  entity-service/src/test/resources/ngsild/apic/beehive.json
  entity-service/src/test/resources/ngsild/aquac/DeadFishes.json
  entity-service/src/test/resources/ngsild/aquac/FeedingService.json
  entity-service/src/test/resources/ngsild/aquac/Sensor.json
  entity-service/src/test/resources/ngsild/aquac/Specie.json
  entity-service/src/test/resources/ngsild/beehive_missing_context.jsonld
  search-service/src/main/kotlin/com/egm/stellio/search/listener/EntityListener.kt
  search-service/src/main/kotlin/com/egm/stellio/search/model/AttributeInstance.kt
  search-service/src/main/kotlin/com/egm/stellio/search/model/TemporalQuery.kt
  search-service/src/main/kotlin/com/egm/stellio/search/service/TemporalEntityAttributeService.kt
  search-service/src/test/kotlin/com/egm/stellio/search/listener/EntityListenerTest.kt
  search-service/src/test/kotlin/com/egm/stellio/search/service/AttributeInstanceServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/service/TemporalEntityAttributeServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/web/TemporalEntityHandlerTests.kt
  search-service/src/test/resources/ngsild/beehive.jsonld
  search-service/src/test/resources/ngsild/beehive2_two_temporal_properties.jsonld
  search-service/src/test/resources/ngsild/beehive_two_temporal_properties.jsonld
  search-service/src/test/resources/ngsild/expectations/beehive_with_incoming_temporal_values.jsonld
  search-service/src/test/resources/ngsild/expectations/subscription_with_notifications.jsonld
  search-service/src/test/resources/ngsild/expectations/subscription_with_notifications_temporal_values.jsonld
  shared/src/main/kotlin/com/egm/stellio/shared/model/Notification.kt
  shared/src/main/kotlin/com/egm/stellio/shared/model/Observation.kt
  shared/src/main/kotlin/com/egm/stellio/shared/util/ApiUtils.kt
  shared/src/main/kotlin/com/egm/stellio/shared/util/NgsiLdParsingUtils.kt
  subscription-service/src/main/kotlin/com/egm/stellio/subscription/model/NotificationParams.kt
  subscription-service/src/main/kotlin/com/egm/stellio/subscription/service/SubscriptionService.kt
  subscription-service/src/main/kotlin/com/egm/stellio/subscription/utils/QueryUtils.kt
  subscription-service/src/test/kotlin/com/egm/stellio/subscription/service/SubscriptionServiceTests.kt
  subscription-service/src/test/resources/ngsild/apic/BeekeeperUpdateEvent.json
  subscription-service/src/test/resources/ngsild/aquac/FeedingService.json
Labels: fix

#19 Feature/18 handle users permissions when requesting subscriptions instances
  shared/src/main/kotlin/com/egm/stellio/shared/model/APiExceptions.kt
  shared/src/main/kotlin/com/egm/stellio/shared/model/ErrorResponse.kt
  shared/src/main/kotlin/com/egm/stellio/shared/util/ApiUtils.kt
  subscription-service/src/main/kotlin/com/egm/stellio/subscription/service/SubscriptionService.kt
  subscription-service/src/main/kotlin/com/egm/stellio/subscription/web/SubscriptionHandler.kt
  subscription-service/src/test/kotlin/com/egm/stellio/subscription/service/SubscriptionServiceTests.kt
  subscription-service/src/test/kotlin/com/egm/stellio/subscription/web/SubscriptionHandlerTests.kt
Labels: feature

#43 fix(subscription): fix call to getById function in subscriptionServiceTests
  subscription-service/src/test/kotlin/com/egm/stellio/subscription/service/SubscriptionServiceTests.kt
Labels: fix

#40 Feature/25 implement all rules related to http request preconditions
  entity-service/src/main/kotlin/com/egm/stellio/entity/web/EntityHandler.kt
  entity-service/src/main/kotlin/com/egm/stellio/entity/web/EntityOperationHandler.kt
  entity-service/src/main/kotlin/com/egm/stellio/entity/web/Routes.kt
  search-service/src/main/kotlin/com/egm/stellio/search/web/Routes.kt
  search-service/src/main/kotlin/com/egm/stellio/search/web/TemporalEntityHandler.kt
  search-service/src/test/kotlin/com/egm/stellio/search/web/TemporalEntityHandlerTests.kt
  shared/src/main/kotlin/com/egm/stellio/shared/util/ApiUtils.kt
  shared/src/main/kotlin/com/egm/stellio/shared/web/CustomWebFilter.kt
  shared/src/main/kotlin/com/egm/stellio/shared/web/ExceptionHandler.kt
  shared/src/test/kotlin/com/egm/stellio/shared/util/ApiUtilsTests.kt
  shared/src/test/kotlin/com/egm/stellio/shared/util/MockkedHandler.kt
  subscription-service/src/main/kotlin/com/egm/stellio/subscription/web/Routes.kt
  subscription-service/src/main/kotlin/com/egm/stellio/subscription/web/SubscriptionHandler.kt
Labels: feature

#46 Feature/45 add web flux tests in controllers testing
  entity-service/src/test/kotlin/com/egm/stellio/entity/config/WebSecurityTestConfig.kt
  entity-service/src/test/kotlin/com/egm/stellio/entity/web/EntityHandlerTests.kt
  entity-service/src/test/kotlin/com/egm/stellio/entity/web/EntityOperationHandlerTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/config/WebSecurityTestConfig.kt
  search-service/src/test/kotlin/com/egm/stellio/search/web/TemporalEntityHandlerTests.kt
  subscription-service/src/test/kotlin/com/egm/stellio/subscription/config/WebSecurityTestConfig.kt
  subscription-service/src/test/kotlin/com/egm/stellio/subscription/web/SubscriptionHandlerTests.kt
Labels: feature

#47 fix(entity): disable health management of neo4j database
  entity-service/src/main/resources/application.properties
Labels: fix

#42 Feat/33 refactor and improve the batch entity creation process
  build.gradle.kts
  entity-service/build.gradle.kts
  entity-service/src/main/kotlin/com/egm/stellio/entity/repository/Neo4jRepository.kt
  entity-service/src/main/kotlin/com/egm/stellio/entity/service/EntityOperationService.kt
  entity-service/src/main/kotlin/com/egm/stellio/entity/service/EntityService.kt
  entity-service/src/main/kotlin/com/egm/stellio/entity/util/EntitiesGraphBuilder.kt
  entity-service/src/main/kotlin/com/egm/stellio/entity/util/ParsingUtils.kt
  entity-service/src/main/kotlin/com/egm/stellio/entity/util/ValidationUtils.kt
  entity-service/src/main/kotlin/com/egm/stellio/entity/web/APIResponses.kt
  entity-service/src/main/kotlin/com/egm/stellio/entity/web/EntityOperationHandler.kt
  entity-service/src/test/kotlin/com/egm/stellio/entity/repository/Neo4jRepositoryTests.kt
  entity-service/src/test/kotlin/com/egm/stellio/entity/service/EntityOperationServiceTests.kt
  entity-service/src/test/kotlin/com/egm/stellio/entity/util/EntitiesGraphBuilderTest.kt
  entity-service/src/test/kotlin/com/egm/stellio/entity/web/EntityOperationHandlerTests.kt
  entity-service/src/test/resources/ngsild/hcmr/HCMR_test_file_cyclic_dependency.json
  entity-service/src/test/resources/ngsild/hcmr/HCMR_test_file_not_valid.json
  shared/src/main/kotlin/com/egm/stellio/shared/model/ExpandedEntity.kt
  shared/src/test/kotlin/com/egm/stellio/shared/model/ExpandedEntityTests.kt
Labels: refactoring

#44 Feature/27 integrate testcontainers in all modules
  entity-service/build.gradle.kts
  entity-service/src/test/kotlin/com/egm/stellio/entity/TestContainersConfiguration.kt
  entity-service/src/test/kotlin/com/egm/stellio/entity/config/TestContainersConfiguration.kt
  entity-service/src/test/kotlin/com/egm/stellio/entity/repository/EntityRepositoryTests.kt
  entity-service/src/test/kotlin/com/egm/stellio/entity/repository/Neo4jRepositoryTests.kt
  search-service/build.gradle.kts
  search-service/docker-compose.yml
  search-service/src/test/kotlin/com/egm/stellio/search/config/TestContainersConfiguration.kt
  search-service/src/test/kotlin/com/egm/stellio/search/config/TimescaleBasedTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/service/AttributeInstanceServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/service/TemporalEntityAttributeServiceTests.kt
  shared/build.gradle.kts
  shared/src/testFixtures/kotlin/com/egm/stellio/shared/TestContainers.kt
  subscription-service/build.gradle.kts
  subscription-service/docker-compose.yml
  subscription-service/src/test/kotlin/com/egm/stellio/subscription/config/R2DBCConfiguration.kt
  subscription-service/src/test/kotlin/com/egm/stellio/subscription/config/TestContainersConfiguration.kt
  subscription-service/src/test/kotlin/com/egm/stellio/subscription/config/TimescaleBasedTests.kt
  subscription-service/src/test/kotlin/com/egm/stellio/subscription/service/SubscriptionServiceTests.kt
  subscription-service/src/test/kotlin/com/egm/stellio/subscription/service/TimescaleBasedTests.kt
Labels: feature
