Repository stellio-hub/stellio-context-broker, pull requests merged in 2020-09, with the labels that each got.

#166 feat(entity): add support for (OAuth2) client authorization #167
  entity-service/src/main/kotlin/com/egm/stellio/entity/authorization/AuthorizationService.kt
  entity-service/src/main/kotlin/com/egm/stellio/entity/authorization/Neo4jAuthorizationRepository.kt
  entity-service/src/main/kotlin/com/egm/stellio/entity/authorization/Neo4jAuthorizationService.kt
  entity-service/src/test/kotlin/com/egm/stellio/entity/authorization/Neo4jAuthorizationRepositoryTest.kt
  entity-service/src/test/kotlin/com/egm/stellio/entity/authorization/Neo4jAuthorizationServiceTest.kt
  entity-service/src/test/kotlin/com/egm/stellio/entity/service/IAMListenerTests.kt
  entity-service/src/test/resources/ngsild/authorization/ClientCreateEvent.json
  entity-service/src/test/resources/ngsild/authorization/ClientDeleteEvent.json
  entity-service/src/test/resources/ngsild/authorization/RealmRoleAppendToClient.json
Labels: feature

#169 Fix/end of line
  .env
  .gitattributes
  API_Quick_Start.md
  README.md
  entity-service/README.md
  entity-service/src/main/kotlin/com/egm/stellio/entity/repository/Neo4jRepository.kt
  entity-service/src/main/kotlin/com/egm/stellio/entity/service/EntityService.kt
  entity-service/src/main/kotlin/com/egm/stellio/entity/web/EntityHandler.kt
  entity-service/src/main/kotlin/com/egm/stellio/entity/web/EntityOperationHandler.kt
  entity-service/src/test/kotlin/com/egm/stellio/entity/web/EntityHandlerTests.kt
  entity-service/src/test/resources/mock/response_entities_by_label.json
  entity-service/src/test/resources/mock/response_entities_by_label_rel_uri.json
  entity-service/src/test/resources/ngsild/HCMR.json
  entity-service/src/test/resources/ngsild/aquac/BreedingService.json
  entity-service/src/test/resources/ngsild/aquac/BreedingService_propWithProp.json
  entity-service/src/test/resources/ngsild/aquac/DeadFishes.json
  entity-service/src/test/resources/ngsild/aquac/Feeder.json
  entity-service/src/test/resources/ngsild/aquac/FeedingService.json
  entity-service/src/test/resources/ngsild/aquac/FishContainment.json
  entity-service/src/test/resources/ngsild/aquac/MortalityRemovalService_standalone.json
  entity-service/src/test/resources/ngsild/aquac/MortalityService.json
  entity-service/src/test/resources/ngsild/aquac/MortalityService_relWithProp.json
  entity-service/src/test/resources/ngsild/aquac/Observation.json
  entity-service/src/test/resources/ngsild/aquac/Observation_missingAttributes.json
  entity-service/src/test/resources/ngsild/aquac/Sensor.json
  entity-service/src/test/resources/ngsild/aquac/Specie.json
  entity-service/src/test/resources/ngsild/hcmr/HCMR_test_file.json
  entity-service/src/test/resources/ngsild/hcmr/HCMR_test_file_missing_context.json
  gradlew.bat
  shared/src/main/kotlin/com/egm/stellio/shared/model/APiExceptions.kt
Labels: fix

#171 feat(common): improve produced Docker images
  api-gateway/build.gradle.kts
  build.gradle.kts
  entity-service/build.gradle.kts
  search-service/build.gradle.kts
  subscription-service/build.gradle.kts
Labels: feature

#170 fix: allow to use subscription service when authentication is disabled
  shared/src/main/kotlin/com/egm/stellio/shared/web/AuthUtils.kt
  subscription-service/src/main/kotlin/com/egm/stellio/subscription/web/SubscriptionHandler.kt
Labels: fix

#177 fix(search): use correct column name when getting an entity payload #176
  search-service/src/main/kotlin/com/egm/stellio/search/service/TemporalEntityAttributeService.kt
Labels: fix, search

#178 Feature/63 endpoint batch entity delete bis
  entity-service/src/main/kotlin/com/egm/stellio/entity/authorization/AuthorizationService.kt
  entity-service/src/main/kotlin/com/egm/stellio/entity/authorization/Neo4jAuthorizationService.kt
  entity-service/src/main/kotlin/com/egm/stellio/entity/authorization/StandaloneAuthorizationService.kt
  entity-service/src/main/kotlin/com/egm/stellio/entity/repository/Neo4jRepository.kt
  entity-service/src/main/kotlin/com/egm/stellio/entity/service/EntityOperationService.kt
  entity-service/src/main/kotlin/com/egm/stellio/entity/service/EntityService.kt
  entity-service/src/main/kotlin/com/egm/stellio/entity/util/EntitiesGraphBuilder.kt
  entity-service/src/main/kotlin/com/egm/stellio/entity/web/APIResponses.kt
  entity-service/src/main/kotlin/com/egm/stellio/entity/web/EntityOperationHandler.kt
  entity-service/src/test/kotlin/com/egm/stellio/entity/repository/Neo4jRepositoryTests.kt
  entity-service/src/test/kotlin/com/egm/stellio/entity/service/EntityOperationServiceTests.kt
  entity-service/src/test/kotlin/com/egm/stellio/entity/util/EntitiesGraphBuilderTest.kt
  entity-service/src/test/kotlin/com/egm/stellio/entity/web/EntityOperationHandlerTests.kt
  entity-service/src/test/resources/ngsild/hcmr/HCMR_test_delete_all_entities.json
Labels: feature

#184 fix(entity): update entity properties in a single cypher query
  entity-service/src/main/kotlin/com/egm/stellio/entity/repository/Neo4jRepository.kt
  entity-service/src/main/kotlin/com/egm/stellio/entity/service/EntityService.kt
  entity-service/src/test/kotlin/com/egm/stellio/entity/repository/Neo4jRepositoryTests.kt
  entity-service/src/test/kotlin/com/egm/stellio/entity/service/EntityServiceTests.kt
Labels: entity, fix

#183 feat(subscription): add system attributes createdAt & modifie…
  shared/src/main/kotlin/com/egm/stellio/shared/util/JsonLdUtils.kt
  shared/src/main/kotlin/com/egm/stellio/shared/util/JsonUtils.kt
  subscription-service/src/main/kotlin/com/egm/stellio/subscription/model/Subscription.kt
  subscription-service/src/main/kotlin/com/egm/stellio/subscription/service/SubscriptionService.kt
  subscription-service/src/main/kotlin/com/egm/stellio/subscription/web/SubscriptionHandler.kt
  subscription-service/src/main/resources/db/migration/V0_11__add_system_attributes_to_subscription_table.sql
  subscription-service/src/test/kotlin/com/egm/stellio/subscription/model/SubscriptionTest.kt
  subscription-service/src/test/kotlin/com/egm/stellio/subscription/service/SubscriptionServiceTests.kt
  subscription-service/src/test/kotlin/com/egm/stellio/subscription/utils/FixtureUtils.kt
  subscription-service/src/test/kotlin/com/egm/stellio/subscription/web/SubscriptionHandlerTests.kt
Labels: feature

#187 fix(entity): remove rewrite naming rules for relationships type #182
  docker-compose.yml
  entity-service/docker-compose.yml
  entity-service/src/main/kotlin/com/egm/stellio/entity/authorization/Neo4jAuthorizationRepository.kt
  entity-service/src/main/kotlin/com/egm/stellio/entity/model/Relationship.kt
  entity-service/src/main/kotlin/com/egm/stellio/entity/repository/Neo4jRepository.kt
  entity-service/src/main/kotlin/com/egm/stellio/entity/service/EntityService.kt
  entity-service/src/main/resources/neo4j/migrations/V05__rename_relationships_type.cypher
  entity-service/src/test/kotlin/com/egm/stellio/entity/service/EntityServiceTests.kt
Labels: entity, fix

#186 feat(subscription): add support for Notification params attributes & format #32
  shared/src/main/kotlin/com/egm/stellio/shared/model/JsonLdEntity.kt
  shared/src/main/kotlin/com/egm/stellio/shared/util/JsonLdUtils.kt
  shared/src/test/kotlin/com/egm/stellio/shared/util/JsonLdUtilsTests.kt
  subscription-service/src/main/kotlin/com/egm/stellio/subscription/service/NotificationService.kt
  subscription-service/src/test/kotlin/com/egm/stellio/subscription/service/NotificationServiceTests.kt
  subscription-service/src/test/kotlin/com/egm/stellio/subscription/service/SubscriptionServiceTests.kt
  subscription-service/src/test/kotlin/com/egm/stellio/subscription/utils/FixtureUtils.kt
  subscription-service/src/test/kotlin/com/egm/stellio/subscription/utils/QueryUtilsTests.kt
Labels: feature

#193 fix(common): use latest tagged images instead of dev #192
  kubernetes/api-gateway-deployment.yaml
  kubernetes/entity-service-deployment.yaml
  kubernetes/search-service-deployment.yaml
  kubernetes/stellio-configmap.yaml
  kubernetes/subscription-service-deployment.yaml
Labels: fix

#201 fix: load neo4j apoc plugin in k8s deployment #194
  kubernetes/neo4j-deployment.yaml
  kubernetes/stellio-configmap.yaml
Labels: fix

#203 feat(common): upgrade to Spring Boot 2.3 #51
  build.gradle.kts
  entity-service/build.gradle.kts
  entity-service/src/main/resources/application.properties
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  search-service/build.gradle.kts
  search-service/src/main/resources/application.properties
  shared/build.gradle.kts
  subscription-service/build.gradle.kts
  subscription-service/src/main/kotlin/com/egm/stellio/subscription/service/SubscriptionService.kt
  subscription-service/src/main/resources/application.properties
Labels: common, feature

#210 feat(search): add support for lastN parameter in temporal entity retrieving #209
  search-service/src/main/kotlin/com/egm/stellio/search/model/TemporalQuery.kt
  search-service/src/main/kotlin/com/egm/stellio/search/service/AttributeInstanceService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/web/TemporalEntityHandler.kt
  search-service/src/test/kotlin/com/egm/stellio/search/service/AttributeInstanceServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/web/TemporalEntityHandlerTests.kt
Labels: feature

#211 feat(search): add attrs support in temporal entity retrieving #207
  search-service/src/main/kotlin/com/egm/stellio/search/model/TemporalQuery.kt
  search-service/src/main/kotlin/com/egm/stellio/search/service/TemporalEntityAttributeService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/web/TemporalEntityHandler.kt
  search-service/src/test/kotlin/com/egm/stellio/search/service/AttributeInstanceServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/service/TemporalEntityAttributeServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/web/TemporalEntityHandlerTests.kt
Labels: feature

#213 fix(entity): delete the property instance of the given datasetId when appending entity attributes #212
  entity-service/src/main/kotlin/com/egm/stellio/entity/service/EntityService.kt
  entity-service/src/test/kotlin/com/egm/stellio/entity/service/EntityServiceTests.kt
Labels: entity, fix
