Repository stellio-hub/stellio-context-broker, pull requests merged in 2020-10, with the labels that each got.

#214 feat(subscription): JSON-LD @context resolution as per 6.3.5 #146
  shared/src/main/kotlin/com/egm/stellio/shared/util/ApiUtils.kt
  subscription-service/src/main/kotlin/com/egm/stellio/subscription/utils/ParsingUtils.kt
  subscription-service/src/main/kotlin/com/egm/stellio/subscription/web/SubscriptionHandler.kt
  subscription-service/src/test/kotlin/com/egm/stellio/subscription/web/SubscriptionHandlerTests.kt
  subscription-service/src/test/resources/ngsild/subscription.json
  subscription-service/src/test/resources/ngsild/subscription_update.json
Labels: feature

#215 fix(subscription): attributes field of NotificationParams datatype is optional (5.2.14.1)
  subscription-service/src/main/kotlin/com/egm/stellio/subscription/model/NotificationParams.kt
  subscription-service/src/main/kotlin/com/egm/stellio/subscription/model/Subscription.kt
  subscription-service/src/main/kotlin/com/egm/stellio/subscription/service/NotificationService.kt
  subscription-service/src/main/kotlin/com/egm/stellio/subscription/service/SubscriptionService.kt
Labels: fix

#216 fix(common): ensure correct serialization of timestamps (e.g without truncation if at second zero)
  entity-service/src/test/kotlin/com/egm/stellio/entity/service/EntityServiceTests.kt
  entity-service/src/test/kotlin/com/egm/stellio/entity/service/ObservationListenerTests.kt
  search-service/src/main/kotlin/com/egm/stellio/search/service/TemporalEntityAttributeService.kt
  search-service/src/test/kotlin/com/egm/stellio/search/service/AttributeInstanceServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/service/TemporalEntityAttributeServiceTests.kt
  search-service/src/test/resources/ngsild/expectations/beehive_with_incoming_temporal_values.jsonld
  subscription-service/src/main/kotlin/com/egm/stellio/subscription/service/NotificationService.kt
Labels: fix

#202 feat: integrate SonarCube into project workflow
  .github/workflows/sonar.yml
Labels: feature, quality

#220 fix(shared): throw an InvalidRequestException when request payload is not a valid JSON document #188
  entity-service/src/test/kotlin/com/egm/stellio/entity/web/EntityOperationHandlerTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/web/TemporalEntityHandlerTests.kt
  shared/src/main/kotlin/com/egm/stellio/shared/model/ErrorResponse.kt
  shared/src/main/kotlin/com/egm/stellio/shared/util/JsonLdUtils.kt
  shared/src/main/kotlin/com/egm/stellio/shared/web/ExceptionHandler.kt
  shared/src/test/kotlin/com/egm/stellio/shared/util/JsonLdUtilsTests.kt
  shared/src/test/kotlin/com/egm/stellio/shared/util/MockkedHandler.kt
  shared/src/test/kotlin/com/egm/stellio/shared/web/ExceptionHandlerTests.kt
Labels: common, fix

#222 feat(entity): migrate web handlers to Kotlin coroutines #221
  entity-service/config/detekt/baseline.xml
  entity-service/src/main/kotlin/com/egm/stellio/entity/web/APIResponses.kt
  entity-service/src/main/kotlin/com/egm/stellio/entity/web/EntityHandler.kt
  entity-service/src/main/kotlin/com/egm/stellio/entity/web/EntityOperationHandler.kt
  entity-service/src/test/kotlin/com/egm/stellio/entity/web/EntityHandlerTests.kt
  shared/src/main/kotlin/com/egm/stellio/shared/util/ApiResponses.kt
  shared/src/main/kotlin/com/egm/stellio/shared/util/ApiUtils.kt
Labels: feature

#226 feat(subscription): migrate web handlers to Kotlin coroutines #223
  subscription-service/src/main/kotlin/com/egm/stellio/subscription/web/APIResponses.kt
  subscription-service/src/main/kotlin/com/egm/stellio/subscription/web/SubscriptionHandler.kt
  subscription-service/src/test/kotlin/com/egm/stellio/subscription/web/SubscriptionHandlerTests.kt
  subscription-service/src/test/resources/ngsild/subscription.json
Labels: feature, subscription

#227 feat(search): migrate search endpoints functions to coroutines closes #224
  entity-service/src/main/kotlin/com/egm/stellio/entity/web/EntityHandler.kt
  entity-service/src/test/kotlin/com/egm/stellio/entity/web/EntityHandlerTests.kt
  search-service/src/main/kotlin/com/egm/stellio/search/web/TemporalEntityHandler.kt
  search-service/src/test/kotlin/com/egm/stellio/search/web/TemporalEntityHandlerTests.kt
  shared/src/main/kotlin/com/egm/stellio/shared/util/ApiResponses.kt
Labels: feature

#218 feat(entity): allow to reference entities not known in the local context broker #217
  entity-service/build.gradle.kts
  entity-service/src/main/kotlin/com/egm/stellio/entity/model/PartialEntity.kt
  entity-service/src/main/kotlin/com/egm/stellio/entity/repository/EntityRepository.kt
  entity-service/src/main/kotlin/com/egm/stellio/entity/repository/Neo4jRepository.kt
  entity-service/src/main/kotlin/com/egm/stellio/entity/repository/PartialEntityRepository.kt
  entity-service/src/main/kotlin/com/egm/stellio/entity/service/EntityOperationService.kt
  entity-service/src/main/kotlin/com/egm/stellio/entity/service/EntityService.kt
  entity-service/src/main/kotlin/com/egm/stellio/entity/util/EntitiesGraphBuilder.kt
  entity-service/src/main/kotlin/com/egm/stellio/entity/web/EntityHandler.kt
  entity-service/src/main/kotlin/com/egm/stellio/entity/web/EntityOperationHandler.kt
  entity-service/src/test/kotlin/com/egm/stellio/entity/repository/Neo4jRepositoryTests.kt
  entity-service/src/test/kotlin/com/egm/stellio/entity/service/EntityOperationServiceTests.kt
  entity-service/src/test/kotlin/com/egm/stellio/entity/service/EntityServiceTests.kt
  entity-service/src/test/kotlin/com/egm/stellio/entity/util/EntitiesGraphBuilderTest.kt
  entity-service/src/test/kotlin/com/egm/stellio/entity/web/EntityHandlerTests.kt
  entity-service/src/test/kotlin/com/egm/stellio/entity/web/EntityOperationHandlerTests.kt
  shared/src/main/kotlin/com/egm/stellio/shared/util/JsonUtils.kt
Labels: feature

#231 fix(search): fix regression in get temporal entity evolution closes #229
  search-service/src/main/kotlin/com/egm/stellio/search/web/TemporalEntityHandler.kt
  search-service/src/test/kotlin/com/egm/stellio/search/web/TemporalEntityHandlerTests.kt
  search-service/src/test/resources/ngsild/beehive_with_two_temporal_attributes_evolution.jsonld
Labels: fix

#233 fix(shared): update fiware context
  shared/src/test/kotlin/com/egm/stellio/shared/util/ApiUtilsTests.kt
  shared/src/testFixtures/kotlin/com/egm/stellio/shared/util/TestUtils.kt
Labels: common, fix

#241 fix(search): make timerel and time optional with default values closes 235
  search-service/src/main/kotlin/com/egm/stellio/search/model/TemporalQuery.kt
  search-service/src/main/kotlin/com/egm/stellio/search/service/AttributeInstanceService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/web/TemporalEntityHandler.kt
  search-service/src/test/kotlin/com/egm/stellio/search/service/AttributeInstanceServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/web/TemporalEntityHandlerTests.kt
Labels: fix
