Repository stellio-hub/stellio-context-broker, pull requests merged in 2020-08, with the labels that each got.

#147 feat: complete support for JSON-LD @context resolution (6.3.5) #146
  entity-service/src/main/kotlin/com/egm/stellio/entity/service/EntityService.kt
  entity-service/src/main/kotlin/com/egm/stellio/entity/web/EntityHandler.kt
  entity-service/src/test/kotlin/com/egm/stellio/entity/web/EntityHandlerTests.kt
  search-service/src/main/kotlin/com/egm/stellio/search/web/TemporalEntityHandler.kt
  search-service/src/test/kotlin/com/egm/stellio/search/web/TemporalEntityHandlerTests.kt
  shared/src/main/kotlin/com/egm/stellio/shared/util/ApiUtils.kt
  shared/src/main/kotlin/com/egm/stellio/shared/util/JsonLdUtils.kt
  subscription-service/src/test/kotlin/com/egm/stellio/subscription/web/SubscriptionHandlerTests.kt
Labels: feature

#148 fix: use in error target relationship name when it fails the creation of an entity
  entity-service/src/main/kotlin/com/egm/stellio/entity/service/EntityService.kt
  entity-service/src/main/kotlin/com/egm/stellio/entity/util/EntitiesGraphBuilder.kt
  entity-service/src/test/kotlin/com/egm/stellio/entity/service/EntityServiceTests.kt
  entity-service/src/test/kotlin/com/egm/stellio/entity/util/EntitiesGraphBuilderTest.kt
Labels: entity, fix

#149 fix search entities behaviour when a matching entity is deleted
  entity-service/src/main/kotlin/com/egm/stellio/entity/repository/EntityRepository.kt
  entity-service/src/main/kotlin/com/egm/stellio/entity/service/EntityService.kt
  entity-service/src/main/kotlin/com/egm/stellio/entity/service/RepositoryEventsListener.kt
  entity-service/src/main/kotlin/com/egm/stellio/entity/web/EntityHandler.kt
  entity-service/src/test/kotlin/com/egm/stellio/entity/web/EntityHandlerTests.kt
Labels: entity, fix

#145 feat(entity): add authorization support - iteration 1
  entity-service/src/main/kotlin/com/egm/stellio/entity/authorization/AuthorizationService.kt
  entity-service/src/main/kotlin/com/egm/stellio/entity/authorization/Neo4jAuthorizationRepository.kt
  entity-service/src/main/kotlin/com/egm/stellio/entity/authorization/Neo4jAuthorizationService.kt
  entity-service/src/main/kotlin/com/egm/stellio/entity/authorization/StandaloneAuthorizationService.kt
  entity-service/src/main/kotlin/com/egm/stellio/entity/service/EntityService.kt
  entity-service/src/main/kotlin/com/egm/stellio/entity/service/IAMEventSink.kt
  entity-service/src/main/kotlin/com/egm/stellio/entity/service/IAMListener.kt
  entity-service/src/main/kotlin/com/egm/stellio/entity/service/ObservationListener.kt
  entity-service/src/main/kotlin/com/egm/stellio/entity/util/ApiTestsBootstrapper.kt
  entity-service/src/main/kotlin/com/egm/stellio/entity/web/EntityHandler.kt
  entity-service/src/main/kotlin/com/egm/stellio/entity/web/EntityOperationHandler.kt
  entity-service/src/main/resources/application-api-tests.properties
  entity-service/src/test/kotlin/com/egm/stellio/entity/authorization/Neo4jAuthorizationRepositoryTest.kt
  entity-service/src/test/kotlin/com/egm/stellio/entity/authorization/Neo4jAuthorizationServiceTest.kt
  entity-service/src/test/kotlin/com/egm/stellio/entity/service/IAMListenerTests.kt
  entity-service/src/test/kotlin/com/egm/stellio/entity/service/ObservationListenerTests.kt
  entity-service/src/test/kotlin/com/egm/stellio/entity/web/EntityHandlerTests.kt
  entity-service/src/test/kotlin/com/egm/stellio/entity/web/EntityOperationHandlerTests.kt
  entity-service/src/test/resources/ngsild/authorization/GroupCreateEvent.json
  entity-service/src/test/resources/ngsild/authorization/GroupDeleteEvent.json
  entity-service/src/test/resources/ngsild/authorization/GroupMembershipAppendEvent.json
  entity-service/src/test/resources/ngsild/authorization/GroupMembershipDeleteEvent.json
  entity-service/src/test/resources/ngsild/authorization/GroupUpdateEvent.json
  entity-service/src/test/resources/ngsild/authorization/RealmRoleUpdateEventNoRole.json
  entity-service/src/test/resources/ngsild/authorization/RealmRoleUpdateEventOneRole.json
  entity-service/src/test/resources/ngsild/authorization/RealmRoleUpdateEventTwoRoles.json
  entity-service/src/test/resources/ngsild/authorization/UserCreateEvent.json
  entity-service/src/test/resources/ngsild/authorization/UserDeleteEvent.json
  shared/build.gradle.kts
  shared/src/main/kotlin/com/egm/stellio/shared/model/EntityEvent.kt
  shared/src/main/kotlin/com/egm/stellio/shared/web/AuthUtils.kt
  shared/src/testFixtures/kotlin/com/egm/stellio/shared/MockSecurityConfig.kt
  subscription-service/src/main/kotlin/com/egm/stellio/subscription/service/NotificationService.kt
  subscription-service/src/main/kotlin/com/egm/stellio/subscription/service/SubscriptionService.kt
  subscription-service/src/test/kotlin/com/egm/stellio/subscription/web/SubscriptionHandlerTests.kt
Labels: feature

#152 fix(subscription): fix warning message when a subscription query contains an unknown attribute #144
  subscription-service/src/main/kotlin/com/egm/stellio/subscription/service/SubscriptionService.kt
  subscription-service/src/main/kotlin/com/egm/stellio/subscription/utils/QueryUtils.kt
Labels: fix, subscription

#161 fix(entity): handle case where an user has a single role
  entity-service/src/main/kotlin/com/egm/stellio/entity/authorization/Neo4jAuthorizationRepository.kt
  entity-service/src/test/kotlin/com/egm/stellio/entity/authorization/Neo4jAuthorizationRepositoryTest.kt
  entity-service/src/test/kotlin/com/egm/stellio/entity/service/IAMListenerTests.kt
  entity-service/src/test/resources/ngsild/authorization/RealmRoleAppendEventNoRole.json
  entity-service/src/test/resources/ngsild/authorization/RealmRoleAppendEventOneRole.json
  entity-service/src/test/resources/ngsild/authorization/RealmRoleAppendEventTwoRoles.json
Labels: fix

#163 fix: improve reliability when reading @context in a JSON-LD input #157
  shared/src/main/kotlin/com/egm/stellio/shared/util/ApiUtils.kt
  shared/src/main/kotlin/com/egm/stellio/shared/util/JsonLdUtils.kt
  shared/src/test/kotlin/com/egm/stellio/shared/util/ApiUtilsTests.kt
Labels: fix
