Repository stellio-hub/stellio-context-broker, pull requests merged in 2021-01, with the labels that each got.

#288 feat: query entities by a list of identifiers #286
  entity-service/src/main/kotlin/com/egm/stellio/entity/repository/Neo4jRepository.kt
  entity-service/src/main/kotlin/com/egm/stellio/entity/service/EntityService.kt
  entity-service/src/main/kotlin/com/egm/stellio/entity/web/EntityHandler.kt
  entity-service/src/test/kotlin/com/egm/stellio/entity/repository/Neo4jRepositoryTests.kt
Labels: entity, feature

#293 fix(common): use CorsFilter of spring security for cors configuration #289
  entity-service/config/detekt/baseline.xml
  entity-service/src/main/kotlin/com/egm/stellio/entity/config/WebConfig.kt
  entity-service/src/main/kotlin/com/egm/stellio/entity/config/WebSecurityConfig.kt
  search-service/config/detekt/baseline.xml
  search-service/src/main/kotlin/com/egm/stellio/search/config/WebConfig.kt
  search-service/src/main/kotlin/com/egm/stellio/search/config/WebSecurityConfig.kt
  subscription-service/src/main/kotlin/com/egm/stellio/subscription/config/WebConfig.kt
  subscription-service/src/main/kotlin/com/egm/stellio/subscription/config/WebSecurityConfig.kt
Labels: common, feature, fix

#291 doc: update quick start samples and data to reflect last API changes
  API_Quick_Start.md
  samples/API_Quick_Start.postman_collection.json
  samples/apiary.jsonld
  samples/apiculture_entities.jsonld
  samples/beehive.jsonld
  samples/beekeeper.jsonld
  samples/sensor_humidity.jsonld
  samples/sensor_temperature.jsonld
  samples/subscription_newEndpoint.jsonld
  samples/subscription_newQuery.jsonld
  samples/subscription_to_beehive.jsonld
Labels: feature

#296 feat: add cors configuration in api gateway #295
  api-gateway/src/main/resources/application.yml
  entity-service/src/main/kotlin/com/egm/stellio/entity/config/WebSecurityConfig.kt
  entity-service/src/main/resources/application.properties
  search-service/src/main/kotlin/com/egm/stellio/search/config/WebSecurityConfig.kt
  search-service/src/main/resources/application.properties
  subscription-service/src/main/kotlin/com/egm/stellio/subscription/config/WebSecurityConfig.kt
  subscription-service/src/main/resources/application.properties
Labels: common, feature

#294 doc: bootstrap roadmap document
  README.md
  docs/roadmap.md
Labels: feature

#299 feat(entity): handle attributeUpdate events coming from observations …
  entity-service/src/main/kotlin/com/egm/stellio/entity/service/ObservationEventListener.kt
  entity-service/src/test/kotlin/com/egm/stellio/entity/service/ObservationEventListenerTests.kt
  entity-service/src/test/resources/ngsild/observations/temperatureUpdateEvent.jsonld
  shared/src/test/kotlin/com/egm/stellio/shared/util/JsonUtilsTests.kt
  shared/src/test/resources/ngsild/events/attributeUpdateEvent.jsonld
  shared/src/testFixtures/kotlin/com/egm/stellio/shared/util/TestUtils.kt
Labels: entity, feature

#302 fix(entity): configure default address for kafka bus
  entity-service/src/main/resources/application.properties
Labels: entity, fix

#301 fix: remove old observations processing
  entity-service/src/main/kotlin/com/egm/stellio/entity/repository/EntityRepository.kt
  entity-service/src/main/kotlin/com/egm/stellio/entity/repository/Neo4jRepository.kt
  entity-service/src/main/kotlin/com/egm/stellio/entity/service/EntityService.kt
  entity-service/src/main/kotlin/com/egm/stellio/entity/service/ObservationListener.kt
  entity-service/src/main/kotlin/com/egm/stellio/entity/service/ObservationsSink.kt
  entity-service/src/test/kotlin/com/egm/stellio/entity/repository/EntityRepositoryTests.kt
  entity-service/src/test/kotlin/com/egm/stellio/entity/repository/Neo4jRepositoryTests.kt
  entity-service/src/test/kotlin/com/egm/stellio/entity/service/EntityServiceTests.kt
  entity-service/src/test/kotlin/com/egm/stellio/entity/service/ObservationListenerTests.kt
  entity-service/src/test/resources/ngsild/aquac/Observation.json
  entity-service/src/test/resources/ngsild/aquac/ObservationWithoutLocation.json
  entity-service/src/test/resources/ngsild/aquac/ObservationWithoutUnitCode.json
  entity-service/src/test/resources/ngsild/aquac/Observation_missingAttributes.json
  shared/src/main/kotlin/com/egm/stellio/shared/util/JsonLdUtils.kt
Labels: fix
