Repository stellio-hub/stellio-context-broker, pull requests merged in 2021-03, with the labels that each got.

#327 fix: retrieve full representation of temporal attributes #240
  search-service/config/detekt/baseline.xml
  search-service/src/main/kotlin/com/egm/stellio/search/model/AttributeInstanceResult.kt
  search-service/src/main/kotlin/com/egm/stellio/search/service/AttributeInstanceService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/service/EntityEventListenerService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/service/TemporalEntityAttributeService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/service/TemporalEntityService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/web/TemporalEntityHandler.kt
  search-service/src/test/kotlin/com/egm/stellio/search/service/AttributeInstanceServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/service/TemporalEntityAttributeServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/service/TemporalEntityServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/util/ParameterizedTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/web/TemporalEntityHandlerTests.kt
  search-service/src/test/resources/ngsild/beehive_with_two_temporal_attributes_evolution.jsonld
  search-service/src/test/resources/ngsild/beehive_with_two_temporal_attributes_evolution_temporal_values.jsonld
  search-service/src/test/resources/ngsild/expectations/beehive_incoming_multi_instances.jsonld
  search-service/src/test/resources/ngsild/expectations/beehive_incoming_multi_instances_string_temporal_values.jsonld
  search-service/src/test/resources/ngsild/expectations/beehive_incoming_multi_instances_string_values.jsonld
  search-service/src/test/resources/ngsild/expectations/beehive_incoming_multi_instances_temporal_values.jsonld
  search-service/src/test/resources/ngsild/expectations/beehive_incoming_multi_instances_without_datasetId.jsonld
  search-service/src/test/resources/ngsild/expectations/beehive_incoming_multi_instances_without_datasetId_temporal_values.jsonld
  search-service/src/test/resources/ngsild/expectations/beehive_with_incoming_temporal_values.jsonld
  search-service/src/test/resources/ngsild/expectations/subscription_empty_notification.jsonld
  search-service/src/test/resources/ngsild/expectations/subscription_with_notifications.jsonld
  search-service/src/test/resources/ngsild/expectations/subscription_with_notifications_aggregated.jsonld
  search-service/src/test/resources/ngsild/expectations/subscription_with_notifications_temporal_values.jsonld
  search-service/src/test/resources/ngsild/expectations/subscription_with_notifications_with_null_values.jsonld
  shared/src/main/kotlin/com/egm/stellio/shared/util/JsonLdUtils.kt
Labels: fix, search

#318 fix: store temporal evolution of attributes metadata #240
  search-service/config/detekt/baseline.xml
  search-service/src/main/kotlin/com/egm/stellio/search/model/AttributeInstance.kt
  search-service/src/main/kotlin/com/egm/stellio/search/model/AttributeInstanceResult.kt
  search-service/src/main/kotlin/com/egm/stellio/search/service/AttributeInstanceService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/service/EntityEventListenerService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/service/SubscriptionEventListenerService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/service/TemporalEntityAttributeService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/service/TemporalEntityService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/web/TemporalEntityHandler.kt
  search-service/src/main/resources/db/migration/V0_14__add_metadata_to_attribute_instance_table.sql
  search-service/src/test/kotlin/com/egm/stellio/search/service/AttributeInstanceServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/service/EntityEventListenerServiceTest.kt
  search-service/src/test/kotlin/com/egm/stellio/search/service/SubscriptionEventListenerServiceTest.kt
  search-service/src/test/kotlin/com/egm/stellio/search/service/TemporalEntityAttributeServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/service/TemporalEntityServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/util/ParameterizedTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/web/TemporalEntityHandlerTests.kt
  search-service/src/test/resources/ngsild/beehive_with_two_temporal_attributes_evolution.jsonld
  search-service/src/test/resources/ngsild/beehive_with_two_temporal_attributes_evolution_temporal_values.jsonld
  search-service/src/test/resources/ngsild/expectations/beehive_incoming_multi_instances.jsonld
  search-service/src/test/resources/ngsild/expectations/beehive_incoming_multi_instances_string_temporal_values.jsonld
  search-service/src/test/resources/ngsild/expectations/beehive_incoming_multi_instances_string_values.jsonld
  search-service/src/test/resources/ngsild/expectations/beehive_incoming_multi_instances_temporal_values.jsonld
  search-service/src/test/resources/ngsild/expectations/beehive_incoming_multi_instances_without_datasetId.jsonld
  search-service/src/test/resources/ngsild/expectations/beehive_incoming_multi_instances_without_datasetId_temporal_values.jsonld
  search-service/src/test/resources/ngsild/expectations/beehive_with_incoming_temporal_values.jsonld
  search-service/src/test/resources/ngsild/expectations/subscription_empty_notification.jsonld
  search-service/src/test/resources/ngsild/expectations/subscription_with_notifications.jsonld
  search-service/src/test/resources/ngsild/expectations/subscription_with_notifications_aggregated.jsonld
  search-service/src/test/resources/ngsild/expectations/subscription_with_notifications_temporal_values.jsonld
  search-service/src/test/resources/ngsild/expectations/subscription_with_notifications_with_null_values.jsonld
  shared/src/main/kotlin/com/egm/stellio/shared/model/JsonLdEntity.kt
  shared/src/main/kotlin/com/egm/stellio/shared/util/JsonLdUtils.kt
Labels: fix, search

#329 feat: add partial support for query temporal entities
  entity-service/src/main/kotlin/com/egm/stellio/entity/web/EntityHandler.kt
  search-service/config/detekt/baseline.xml
  search-service/src/main/kotlin/com/egm/stellio/search/service/TemporalEntityAttributeService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/service/TemporalEntityService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/web/TemporalEntityHandler.kt
  search-service/src/test/kotlin/com/egm/stellio/search/service/TemporalEntityAttributeServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/service/TemporalEntityServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/util/QueryParameterizedTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/web/TemporalEntityHandlerTests.kt
  search-service/src/test/resources/ngsild/expectations/query/two_beehives.json
  search-service/src/test/resources/ngsild/expectations/query/two_beehives_temporal_values.json
  shared/src/main/kotlin/com/egm/stellio/shared/util/ApiUtils.kt
  shared/src/test/kotlin/com/egm/stellio/shared/util/ApiUtilsTests.kt
Labels: feature, search

#335 fix: return all expected temporal entities + switch back to version 1.11.2 for detekt #334
  build.gradle.kts
  search-service/src/main/kotlin/com/egm/stellio/search/service/TemporalEntityAttributeService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/service/TemporalEntityService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/web/TemporalEntityHandler.kt
  search-service/src/test/kotlin/com/egm/stellio/search/service/TemporalEntityAttributeServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/web/TemporalEntityHandlerTests.kt
  search-service/src/test/resources/ngsild/expectations/beehive_incoming_multi_instances_string_temporal_values.jsonld
  search-service/src/test/resources/ngsild/expectations/beehive_incoming_multi_instances_without_datasetId_temporal_values.jsonld
  search-service/src/test/resources/ngsild/expectations/beehive_with_incoming_temporal_values.jsonld
  search-service/src/test/resources/ngsild/expectations/query/two_beehives_temporal_values.json
  search-service/src/test/resources/ngsild/expectations/subscription_with_notifications_aggregated.jsonld
  search-service/src/test/resources/ngsild/expectations/subscription_with_notifications_temporal_values.jsonld
Labels: fix, search

#341 feat(entity): handle specific access policy on entities #340
  entity-service/src/main/kotlin/com/egm/stellio/entity/authorization/AuthorizationService.kt
  entity-service/src/main/kotlin/com/egm/stellio/entity/authorization/Neo4jAuthorizationRepository.kt
  entity-service/src/main/kotlin/com/egm/stellio/entity/authorization/Neo4jAuthorizationService.kt
  entity-service/src/main/kotlin/com/egm/stellio/entity/web/EntityHandler.kt
  entity-service/src/test/kotlin/com/egm/stellio/entity/authorization/Neo4jAuthorizationRepositoryTest.kt
  entity-service/src/test/kotlin/com/egm/stellio/entity/authorization/Neo4jAuthorizationServiceTest.kt
  shared/src/main/kotlin/com/egm/stellio/shared/util/JsonLdUtils.kt
Labels: feature

#342 fix(entity): delete incoming relationships when deleting an entity #162
  entity-service/src/main/kotlin/com/egm/stellio/entity/repository/Neo4jRepository.kt
  entity-service/src/main/resources/neo4j/migrations/V06__remove_dangling_relationships.cypher
  entity-service/src/test/kotlin/com/egm/stellio/entity/repository/Neo4jRepositoryTests.kt
Labels: fix

#344 fix(devops): add missing bootstrap URL for Kafka servers in entity service definition #343
  kubernetes/entity-service-deployment.yaml
Labels: fix

#345 feat(entity): send only attribute instance payload in update / append event #328
  entity-service/src/main/kotlin/com/egm/stellio/entity/service/EntityEventService.kt
  entity-service/src/main/kotlin/com/egm/stellio/entity/web/EntityHandler.kt
  entity-service/src/test/kotlin/com/egm/stellio/entity/service/EntityEventServiceTests.kt
  entity-service/src/test/kotlin/com/egm/stellio/entity/web/EntityHandlerTests.kt
  shared/src/main/kotlin/com/egm/stellio/shared/util/JsonLdUtils.kt
  shared/src/test/kotlin/com/egm/stellio/shared/util/JsonLdUtilsTests.kt
Labels: fix

#355 feat: better check attributes provided when updating a subscription #354
  shared/src/main/kotlin/com/egm/stellio/shared/model/APiExceptions.kt
  shared/src/main/kotlin/com/egm/stellio/shared/model/ErrorResponse.kt
  shared/src/main/kotlin/com/egm/stellio/shared/web/ExceptionHandler.kt
  subscription-service/src/main/kotlin/com/egm/stellio/subscription/service/SubscriptionService.kt
  subscription-service/src/test/kotlin/com/egm/stellio/subscription/service/SubscriptionServiceTests.kt
Labels: feature

#358 feat: check entity type and attribute names for invalid characters (4.6.2) #11
  shared/src/main/kotlin/com/egm/stellio/shared/model/NgsiLdEntity.kt
  shared/src/test/kotlin/com/egm/stellio/shared/model/NgsiLdEntityTests.kt
Labels: entity, feature

#360 feat(entity): JSON-LD @context resolution in batch operations #146
  entity-service/src/main/kotlin/com/egm/stellio/entity/web/EntityOperationHandler.kt
  entity-service/src/test/kotlin/com/egm/stellio/entity/web/EntityOperationHandlerTests.kt
  entity-service/src/test/resources/ngsild/hcmr/HCMR_test_file_one_entity_missing_context.json
  shared/src/main/kotlin/com/egm/stellio/shared/util/ApiUtils.kt
  shared/src/main/kotlin/com/egm/stellio/shared/util/JsonLdUtils.kt
Labels: feature
