Repository stellio-hub/stellio-context-broker, pull requests merged in 2022-11, with the labels that each got.

#777 feature/remove sysattrs from attributes
  search-service/src/main/kotlin/db/migration/V0_28__JsonLd_migration.kt
Labels: feature

#789 fix: do not send IAM events to catch-all topic
  entity-service/src/main/kotlin/com/egm/stellio/entity/service/EntityEventService.kt
Labels: fix

#785 fix: add a default creation date if it is not present
  search-service/src/main/kotlin/db/migration/V0_28__JsonLd_migration.kt
Labels: fix

#791 fix: attrs request param no longer processed when querying a temporal entity
  search-service/src/main/kotlin/com/egm/stellio/search/model/TemporalQuery.kt
  search-service/src/main/kotlin/com/egm/stellio/search/service/QueryService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/web/TemporalEntityHandler.kt
  search-service/src/test/kotlin/com/egm/stellio/search/service/QueryServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/service/TemporalEntityServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/web/TemporalEntityHandlerTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/web/TemporalEntityOperationsHandlerTests.kt
Labels: fix, search

#790 fix: handle boolean when adding attribute instance
  search-service/src/main/kotlin/com/egm/stellio/search/util/AttributeInstanceUtils.kt
  search-service/src/test/kotlin/com/egm/stellio/search/service/AttributeInstanceServiceTests.kt
Labels: fix

#778 fix/search by regex query on entities
  search-service/config/detekt/baseline.xml
  search-service/src/main/kotlin/com/egm/stellio/search/service/TemporalEntityAttributeService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/util/DBUtils.kt
  search-service/src/test/kotlin/com/egm/stellio/search/service/TemporalEntityAttributeServiceTests.kt
  search-service/src/test/resources/ngsild/beehive.jsonld
  search-service/src/test/resources/ngsild/beehive_two_temporal_properties.jsonld
  shared/src/main/kotlin/com/egm/stellio/shared/util/JsonLdUtils.kt
  shared/src/testFixtures/kotlin/com/egm/stellio/shared/util/JsonLdContextUtils.kt
  shared/src/testFixtures/resources/contexts/apic.jsonld
Labels: fix

#795 fix(migration): ensure to have only one dataset per attribute instance
  search-service/config/detekt/baseline.xml
  search-service/src/main/kotlin/db/migration/V0_28__JsonLd_migration.kt
  search-service/src/test/kotlin/db/migration/V0_28_JsonLd_migrationTests.kt
  search-service/src/test/resources/ngsild/fragments/attribute_with_default_instance_and_dataset_id.jsonld
  search-service/src/test/resources/ngsild/fragments/attribute_with_two_instances_and_different_dataset_id.jsonld
  search-service/src/test/resources/ngsild/fragments/attribute_with_two_instances_and_same_dataset_id.jsonld
Labels: fix

#798 fix/replace simple quote by two dollar symbol
  search-service/src/main/kotlin/db/migration/V0_28__JsonLd_migration.kt
Labels: fix

#799 fix: move-function-after-attributes-exepansion
  search-service/src/main/kotlin/db/migration/V0_28__JsonLd_migration.kt
  search-service/src/test/kotlin/db/migration/V0_28_JsonLd_migrationTests.kt
  search-service/src/test/resources/ngsild/fragments/attribute_with_two_default_instances.jsonld
Labels: fix
