Repository stellio-hub/stellio-context-broker, pull requests merged in 2022-05, with the labels that each got.

#627 feat(entity): get groups the currently authenticated user belongs to
  entity-service/config/detekt/baseline.xml
  entity-service/src/main/kotlin/com/egm/stellio/entity/authorization/AuthorizationService.kt
  entity-service/src/main/kotlin/com/egm/stellio/entity/authorization/Group.kt
  entity-service/src/main/kotlin/com/egm/stellio/entity/authorization/Neo4jAuthorizationRepository.kt
  entity-service/src/main/kotlin/com/egm/stellio/entity/authorization/Neo4jAuthorizationService.kt
  entity-service/src/main/kotlin/com/egm/stellio/entity/authorization/StandaloneAuthorizationService.kt
  entity-service/src/main/kotlin/com/egm/stellio/entity/web/EntityAccessControlHandler.kt
  entity-service/src/test/kotlin/com/egm/stellio/entity/authorization/AuthorizationServiceTests.kt
  entity-service/src/test/kotlin/com/egm/stellio/entity/authorization/Neo4jAuthorizationRepositoryTest.kt
  entity-service/src/test/kotlin/com/egm/stellio/entity/authorization/Neo4jAuthorizationServiceTest.kt
  entity-service/src/test/kotlin/com/egm/stellio/entity/web/EntityAccessControlHandlerTests.kt
  shared/src/main/kotlin/com/egm/stellio/shared/util/JsonLdUtils.kt
Labels: feature

#593 feat(entity): new acl endpoints #552
  entity-service/config/detekt/baseline.xml
  entity-service/src/main/kotlin/com/egm/stellio/entity/authorization/AuthorizationService.kt
  entity-service/src/main/kotlin/com/egm/stellio/entity/authorization/EntityAccessControl.kt
  entity-service/src/main/kotlin/com/egm/stellio/entity/authorization/Group.kt
  entity-service/src/main/kotlin/com/egm/stellio/entity/authorization/Neo4jAuthorizationRepository.kt
  entity-service/src/main/kotlin/com/egm/stellio/entity/authorization/Neo4jAuthorizationService.kt
  entity-service/src/main/kotlin/com/egm/stellio/entity/authorization/StandaloneAuthorizationService.kt
  entity-service/src/main/kotlin/com/egm/stellio/entity/repository/QueryUtils.kt
  entity-service/src/main/kotlin/com/egm/stellio/entity/service/EntityService.kt
  entity-service/src/main/kotlin/com/egm/stellio/entity/web/BatchAPIResponses.kt
  entity-service/src/main/kotlin/com/egm/stellio/entity/web/EntityAccessControlHandler.kt
  entity-service/src/main/kotlin/com/egm/stellio/entity/web/EntityHandler.kt
  entity-service/src/main/kotlin/com/egm/stellio/entity/web/EntityOperationHandler.kt
  entity-service/src/test/kotlin/com/egm/stellio/entity/authorization/AuthorizationServiceTests.kt
  entity-service/src/test/kotlin/com/egm/stellio/entity/authorization/Neo4jAuthorizationRepositoryTest.kt
  entity-service/src/test/kotlin/com/egm/stellio/entity/authorization/Neo4jAuthorizationServiceTest.kt
  entity-service/src/test/kotlin/com/egm/stellio/entity/service/EntityServiceTests.kt
  entity-service/src/test/kotlin/com/egm/stellio/entity/web/EntityAccessControlHandlerTests.kt
  entity-service/src/test/kotlin/com/egm/stellio/entity/web/EntityHandlerTests.kt
  entity-service/src/test/kotlin/com/egm/stellio/entity/web/EntityOperationHandlerTests.kt
  entity-service/src/test/resources/ngsild/hcmr/HCMR_test_file_invalid_relation_update.json
  entity-service/src/test/resources/ngsild/hcmr/HCMR_test_file_not_valid.json
  shared/src/main/kotlin/com/egm/stellio/shared/model/APiExceptions.kt
  shared/src/main/kotlin/com/egm/stellio/shared/model/JsonLdEntity.kt
  shared/src/main/kotlin/com/egm/stellio/shared/util/ApiResponses.kt
  shared/src/main/kotlin/com/egm/stellio/shared/util/ApiUtils.kt
  shared/src/main/kotlin/com/egm/stellio/shared/util/AuthUtils.kt
  shared/src/main/kotlin/com/egm/stellio/shared/util/JsonLdUtils.kt
  shared/src/test/kotlin/com/egm/stellio/shared/model/JsonLdEntityTests.kt
  shared/src/testFixtures/kotlin/com/egm/stellio/shared/util/JsonLdContextUtils.kt
  subscription-service/src/main/kotlin/com/egm/stellio/subscription/utils/ParsingUtils.kt
  subscription-service/src/main/kotlin/com/egm/stellio/subscription/web/SubscriptionHandler.kt
  subscription-service/src/test/kotlin/com/egm/stellio/subscription/web/SubscriptionHandlerTests.kt
Labels: feature

#642 conf: disable some Detekt rules for tests classes
  config/detekt/detekt.yml
  entity-service/config/detekt/baseline.xml
  search-service/config/detekt/baseline.xml
  shared/config/detekt/baseline.xml
  subscription-service/config/detekt/baseline.xml
Labels: chore, common, quality

#644 fix(entity): handle entities without specific attributes in authz checks
  entity-service/src/main/kotlin/com/egm/stellio/entity/authorization/AuthorizationService.kt
Labels: fix, entity

#643 fix(search): handling of service account ids when checking rights for clients
  search-service/src/main/kotlin/com/egm/stellio/search/service/SubjectReferentialService.kt
  search-service/src/main/resources/db/migration/V0_25__swap_client_and_service_account_info.sql
  search-service/src/test/kotlin/com/egm/stellio/search/service/SubjectReferentialServiceTests.kt
Labels: fix, search

#651 fix(entity): IAM events no longer sent to correct topic
  entity-service/src/main/kotlin/com/egm/stellio/entity/service/EntityEventService.kt
  entity-service/src/main/kotlin/com/egm/stellio/entity/web/EntityAccessControlHandler.kt
  entity-service/src/test/kotlin/com/egm/stellio/entity/service/EntityEventServiceTests.kt
  entity-service/src/test/kotlin/com/egm/stellio/entity/web/EntityAccessControlHandlerTests.kt
  search-service/src/main/kotlin/com/egm/stellio/search/service/IAMListener.kt
  shared/src/main/kotlin/com/egm/stellio/shared/util/AuthUtils.kt
Labels: fix, entity

#653 feat(k8s): minor conifiguration updates to reflect last version of Stellio
  kubernetes/kafka-deployment.yaml
  kubernetes/neo4j-deployment.yaml
  kubernetes/postgres-deployment.yaml
  kubernetes/stellio-configmap.yaml
Labels: feature

#654 fix(search): handle ATTRIBUTE_REPLACE in entity rights events
  search-service/src/main/kotlin/com/egm/stellio/search/service/IAMListener.kt
Labels: fix, search

#655 chore: align imports on IntelliJ default rules
  .editorconfig
  entity-service/src/main/kotlin/com/egm/stellio/entity/model/AttributeList.kt
  entity-service/src/main/kotlin/com/egm/stellio/entity/model/EntityTypeList.kt
  entity-service/src/main/kotlin/com/egm/stellio/entity/model/Property.kt
  entity-service/src/main/kotlin/com/egm/stellio/entity/model/Relationship.kt
  entity-service/src/main/kotlin/com/egm/stellio/entity/service/AttributeService.kt
  entity-service/src/main/kotlin/com/egm/stellio/entity/service/EntityAttributeService.kt
  entity-service/src/main/kotlin/com/egm/stellio/entity/service/EntityEventService.kt
  entity-service/src/main/kotlin/com/egm/stellio/entity/service/IAMListener.kt
  entity-service/src/main/kotlin/com/egm/stellio/entity/service/ObservationEventListener.kt
  entity-service/src/main/kotlin/com/egm/stellio/entity/web/EntityAccessControlHandler.kt
  entity-service/src/main/kotlin/com/egm/stellio/entity/web/EntityHandler.kt
  entity-service/src/main/kotlin/com/egm/stellio/entity/web/EntityOperationHandler.kt
  entity-service/src/main/kotlin/com/egm/stellio/entity/web/EntityTypeHandler.kt
  entity-service/src/test/kotlin/com/egm/stellio/entity/authorization/Neo4jAuthorizationServiceTest.kt
  entity-service/src/test/kotlin/com/egm/stellio/entity/repository/Neo4jSearchRepositoryTests.kt
  entity-service/src/test/kotlin/com/egm/stellio/entity/repository/StandaloneNeo4jSearchRepositoryTests.kt
  entity-service/src/test/kotlin/com/egm/stellio/entity/service/EntityOperationServiceTests.kt
  entity-service/src/test/kotlin/com/egm/stellio/entity/service/EntityServiceTests.kt
  entity-service/src/test/kotlin/com/egm/stellio/entity/service/ObservationEventListenerTests.kt
  entity-service/src/test/kotlin/com/egm/stellio/entity/web/AttributeHandlerTests.kt
  entity-service/src/test/kotlin/com/egm/stellio/entity/web/EntityTypeHandlerTests.kt
  search-service/src/main/kotlin/com/egm/stellio/search/model/AttributeInstance.kt
  search-service/src/main/kotlin/com/egm/stellio/search/service/AttributeInstanceService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/service/EntityAccessRightsService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/service/IAMListener.kt
  search-service/src/main/kotlin/com/egm/stellio/search/service/SubscriptionEventListenerService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/service/TemporalEntityAttributeService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/service/TemporalEntityService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/util/QueryUtils.kt
  search-service/src/main/kotlin/com/egm/stellio/search/web/TemporalEntityHandler.kt
  search-service/src/test/kotlin/com/egm/stellio/search/service/EntityEventListenerServiceTest.kt
  search-service/src/test/kotlin/com/egm/stellio/search/service/EntityServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/service/TemporalEntityServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/web/TemporalEntityHandlerTests.kt
  shared/src/main/kotlin/com/egm/stellio/shared/util/ApiUtils.kt
  shared/src/test/kotlin/com/egm/stellio/shared/model/NgsiLdEntityTests.kt
  shared/src/test/kotlin/com/egm/stellio/shared/util/ApiUtilsTests.kt
  shared/src/test/kotlin/com/egm/stellio/shared/util/JsonLdUtilsTests.kt
  shared/src/test/kotlin/com/egm/stellio/shared/util/MockkedHandler.kt
  shared/src/testFixtures/kotlin/com/egm/stellio/shared/util/TestUtils.kt
  subscription-service/src/main/kotlin/com/egm/stellio/subscription/service/NotificationService.kt
  subscription-service/src/main/kotlin/com/egm/stellio/subscription/service/SubscriptionService.kt
  subscription-service/src/main/kotlin/com/egm/stellio/subscription/utils/ParsingUtils.kt
  subscription-service/src/main/kotlin/com/egm/stellio/subscription/web/SubscriptionHandler.kt
  subscription-service/src/test/kotlin/com/egm/stellio/subscription/model/SubscriptionTest.kt
  subscription-service/src/test/kotlin/com/egm/stellio/subscription/service/SubscriptionEventServiceTests.kt
  subscription-service/src/test/kotlin/com/egm/stellio/subscription/service/SubscriptionServiceTests.kt
  subscription-service/src/test/kotlin/com/egm/stellio/subscription/utils/FixtureUtils.kt
  subscription-service/src/test/kotlin/com/egm/stellio/subscription/web/SubscriptionHandlerTests.kt
Labels: chore, common

#652 feat(search): add endpoint delete entity attribute instance
  search-service/config/detekt/baseline.xml
  search-service/src/main/kotlin/com/egm/stellio/search/service/AttributeInstanceService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/service/EntityAccessRightsService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/service/TemporalEntityAttributeService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/web/TemporalEntityHandler.kt
  search-service/src/test/kotlin/com/egm/stellio/search/service/AttributeInstanceServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/service/EntityAccessRightsServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/service/TemporalEntityAttributeServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/web/TemporalEntityHandlerTests.kt
  shared/src/main/kotlin/com/egm/stellio/shared/util/ApiResponses.kt
Labels: feature, search

#665 feat(entity): add geoProperty operationSpace and observationSpace
  entity-service/config/detekt/baseline.xml
  entity-service/src/main/kotlin/com/egm/stellio/entity/model/Entity.kt
  entity-service/src/main/kotlin/com/egm/stellio/entity/repository/Neo4jRepository.kt
  entity-service/src/main/kotlin/com/egm/stellio/entity/service/EntityService.kt
  entity-service/src/test/kotlin/com/egm/stellio/entity/model/EntityTest.kt
  entity-service/src/test/kotlin/com/egm/stellio/entity/repository/Neo4jRepositoryTests.kt
  entity-service/src/test/kotlin/com/egm/stellio/entity/service/EntityServiceTests.kt
  shared/src/main/kotlin/com/egm/stellio/shared/util/JsonLdUtils.kt
  shared/src/testFixtures/kotlin/com/egm/stellio/shared/util/TestUtils.kt
  subscription-service/src/test/kotlin/com/egm/stellio/subscription/utils/QueryUtilsTests.kt
Labels: feature

#671 fix: compact geo property key
  entity-service/src/main/kotlin/com/egm/stellio/entity/service/EntityService.kt
  entity-service/src/test/kotlin/com/egm/stellio/entity/service/EntityServiceTests.kt
  shared/src/main/kotlin/com/egm/stellio/shared/util/JsonLdUtils.kt
Labels: fix

#670 chore: upgrade to Spring Cloud 2021.0.3
  build.gradle.kts
Labels: chore
