Repository stellio-hub/stellio-context-broker, pull requests merged in 2022-12, with the labels that each got.

#806 fix: missing character in sql query
  search-service/src/main/kotlin/db/migration/V0_28__JsonLd_migration.kt
Labels: fix

#804 fix/problem related to context in entity payload table
  search-service/src/main/kotlin/db/migration/V0_28__JsonLd_migration.kt
  search-service/src/main/resources/db/migration/V0_27__add_support_for_entity_api.sql
Labels: fix

#805 fix/add default creation date in entity_payload table
  search-service/src/main/kotlin/db/migration/V0_28__JsonLd_migration.kt
Labels: fix

#813 feature/launch the ngsi ld test suite job
  Jenkinsfile
Labels: feature

#812 fix(search): update instance_id when updating a past measure (to be in sync with stored payload)
  search-service/src/main/kotlin/com/egm/stellio/search/model/AttributeInstance.kt
  search-service/src/main/kotlin/com/egm/stellio/search/service/AttributeInstanceService.kt
  search-service/src/main/resources/db/migration/V0_27__fix_inconsistent_instance_id_values.sql
Labels: fix, search

#809 fix: actions on update / replace of an attribute
  search-service/config/detekt/baseline.xml
  search-service/src/main/kotlin/com/egm/stellio/search/service/TemporalEntityAttributeService.kt
  search-service/src/test/kotlin/com/egm/stellio/search/service/TemporalEntityAttributeServiceTests.kt
  search-service/src/test/resources/ngsild/fragments/beehive_new_incoming_property.json
  shared/src/main/kotlin/com/egm/stellio/shared/model/NgsiLdEntity.kt
Labels: fix

#820 feat(auth): integration of last authorization features
  search-service/config/detekt/baseline.xml
  search-service/src/main/kotlin/com/egm/stellio/search/authorization/AuthorizationService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/authorization/DisabledAuthorizationService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/authorization/EnabledAuthorizationService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/authorization/EntityAccessControl.kt
  search-service/src/main/kotlin/com/egm/stellio/search/authorization/EntityAccessRights.kt
  search-service/src/main/kotlin/com/egm/stellio/search/authorization/EntityAccessRightsService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/authorization/Group.kt
  search-service/src/main/kotlin/com/egm/stellio/search/authorization/SubjectAccessRight.kt
  search-service/src/main/kotlin/com/egm/stellio/search/authorization/SubjectReferential.kt
  search-service/src/main/kotlin/com/egm/stellio/search/authorization/SubjectReferentialService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/service/EntityEventService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/service/EntityPayloadService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/service/IAMListener.kt
  search-service/src/main/kotlin/com/egm/stellio/search/support/ApiTestsBootstrapper.kt
  search-service/src/main/kotlin/com/egm/stellio/search/util/DBUtils.kt
  search-service/src/main/kotlin/com/egm/stellio/search/web/EntityAccessControlHandler.kt
  search-service/src/test/kotlin/com/egm/stellio/search/authorization/EnabledAuthorizationServiceTest.kt
  search-service/src/test/kotlin/com/egm/stellio/search/authorization/EntityAccessRightsServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/authorization/SubjectInfoUtils.kt
  search-service/src/test/kotlin/com/egm/stellio/search/authorization/SubjectReferentialServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/service/EntityPayloadServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/service/IAMListenerTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/web/EntityAccessControlHandlerTests.kt
  shared/src/main/kotlin/com/egm/stellio/shared/util/AuthUtils.kt
  shared/src/main/kotlin/com/egm/stellio/shared/util/JsonLdUtils.kt
Labels: feature
