Repository stellio-hub/stellio-context-broker, pull requests merged in 2022-07, with the labels that each got.

#710 feat(entity): add support for regex matching on attributes values
  entity-service/src/main/kotlin/com/egm/stellio/entity/util/ParsingUtils.kt
  entity-service/src/test/kotlin/com/egm/stellio/entity/repository/StandaloneNeo4jSearchRepositoryTests.kt
Labels: feature, entity

#714 feat: add the possibility to make queries only on ids
  entity-service/config/detekt/baseline.xml
  entity-service/src/main/kotlin/com/egm/stellio/entity/web/EntityHandler.kt
  entity-service/src/test/kotlin/com/egm/stellio/entity/repository/Neo4jSearchRepositoryTests.kt
  entity-service/src/test/kotlin/com/egm/stellio/entity/web/EntityHandlerTests.kt
Labels: feature

#718 fix(search): apply pagination on entities whatever their matching attributes
  search-service/src/main/kotlin/com/egm/stellio/search/service/TemporalEntityAttributeService.kt
  search-service/src/test/kotlin/com/egm/stellio/search/service/TemporalEntityAttributeServiceTests.kt
Labels: fix, search

#720 feat(search): add support for `idPattern` in queries on temporal entities
  search-service/src/main/kotlin/com/egm/stellio/search/service/TemporalEntityAttributeService.kt
  search-service/src/test/kotlin/com/egm/stellio/search/service/TemporalEntityAttributeServiceTests.kt
Labels: feature

#722 fix(search): remove prefix if empty query filter
  search-service/src/main/kotlin/com/egm/stellio/search/service/TemporalEntityAttributeService.kt
  search-service/src/test/kotlin/com/egm/stellio/search/service/TemporalEntityAttributeServiceTests.kt
Labels: fix

#723 fix(search): ensure ordering of temporal entities returned
  search-service/src/main/kotlin/com/egm/stellio/search/service/QueryService.kt
Labels: fix
