Repository stellio-hub/stellio-context-broker, pull requests merged in 2022-06, with the labels that each got.

#672 fix: add datasetid to endpoint get authorized entities
  entity-service/config/detekt/baseline.xml
  entity-service/src/main/kotlin/com/egm/stellio/entity/authorization/EntityAccessControl.kt
  entity-service/src/main/kotlin/com/egm/stellio/entity/authorization/Neo4jAuthorizationRepository.kt
  entity-service/src/test/kotlin/com/egm/stellio/entity/authorization/Neo4jAuthorizationRepositoryTest.kt
  entity-service/src/test/kotlin/com/egm/stellio/entity/authorization/Neo4jAuthorizationServiceTest.kt
  entity-service/src/test/kotlin/com/egm/stellio/entity/web/EntityAccessControlHandlerTests.kt
Labels: fix

#674 fix(entity): updated modifiedAt whenether it needs to
  entity-service/src/main/kotlin/com/egm/stellio/entity/service/EntityService.kt
  entity-service/src/test/kotlin/com/egm/stellio/entity/service/EntityServiceTests.kt
Labels: fix

#698 fix(entity): use context from NGSI-LD entity when publishing batch creation event
  entity-service/src/main/kotlin/com/egm/stellio/entity/web/EntityOperationHandler.kt
Labels: fix, entity

#669 feat(subscription): handle all core geoproperties
  shared/src/main/kotlin/com/egm/stellio/shared/model/NgsiLdEntity.kt
  shared/src/main/kotlin/com/egm/stellio/shared/util/JsonLdUtils.kt
  shared/src/test/kotlin/com/egm/stellio/shared/model/NgsiLdEntityTests.kt
  subscription-service/src/main/kotlin/com/egm/stellio/subscription/model/GeoQuery.kt
  subscription-service/src/main/kotlin/com/egm/stellio/subscription/model/Subscription.kt
  subscription-service/src/main/kotlin/com/egm/stellio/subscription/service/NotificationService.kt
  subscription-service/src/main/kotlin/com/egm/stellio/subscription/service/SubscriptionService.kt
  subscription-service/src/main/kotlin/com/egm/stellio/subscription/utils/ParsingUtils.kt
  subscription-service/src/main/kotlin/com/egm/stellio/subscription/utils/QueryUtils.kt
  subscription-service/src/main/resources/db/migration/V0_16__initialize_geo_property.sql
  subscription-service/src/test/kotlin/com/egm/stellio/subscription/model/SubscriptionTest.kt
  subscription-service/src/test/kotlin/com/egm/stellio/subscription/service/SubscriptionServiceTests.kt
Labels: feature

#705 fix(entity): allow to add / remove a service account to / from a group
  entity-service/src/main/kotlin/com/egm/stellio/entity/service/IAMListener.kt
  entity-service/src/test/kotlin/com/egm/stellio/entity/service/IAMListenerTests.kt
Labels: fix, entity
