Repository stellio-hub/stellio-context-broker, pull requests merged in 2023-01, with the labels that each got.

#822 feat: no longer support the sys attrs request parameter
  search-service/config/detekt/baseline.xml
  search-service/src/main/kotlin/com/egm/stellio/search/authorization/EnabledAuthorizationService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/authorization/EntityAccessRights.kt
  search-service/src/main/kotlin/com/egm/stellio/search/authorization/EntityAccessRightsService.kt
  search-service/src/test/kotlin/com/egm/stellio/search/authorization/EnabledAuthorizationServiceTest.kt
  search-service/src/test/kotlin/com/egm/stellio/search/authorization/EntityAccessRightsServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/web/EntityAccessControlHandlerTests.kt
Labels: feature

#824 fix: error on data type output cast in SQL query
  search-service/src/main/kotlin/com/egm/stellio/search/authorization/SubjectReferentialService.kt
  search-service/src/test/kotlin/com/egm/stellio/search/authorization/SubjectReferentialServiceTests.kt
Labels: fix

#825 fix : do not bind entities ids if empty in EntityAccessRightsService
  search-service/src/main/kotlin/com/egm/stellio/search/authorization/EntityAccessRightsService.kt
  search-service/src/test/kotlin/com/egm/stellio/search/authorization/EntityAccessRightsServiceTests.kt
Labels: fix

#826 fix: check SAP return nothing when list is empty
  search-service/src/main/kotlin/com/egm/stellio/search/service/EntityPayloadService.kt
  search-service/src/test/kotlin/com/egm/stellio/search/service/EntityPayloadServiceTests.kt
Labels: fix

#823 feat: update bootstrap file for auth test suite
  search-service/src/main/kotlin/com/egm/stellio/search/support/ApiTestsBootstrapper.kt
Labels: feature

#828 feat: add username and group name to tests subjects
  search-service/src/main/kotlin/com/egm/stellio/search/support/ApiTestsBootstrapper.kt
Labels: feature

#827 fix: expand correctly subjectInfo
  search-service/src/main/kotlin/com/egm/stellio/search/authorization/EntityAccessRights.kt
  search-service/src/main/kotlin/com/egm/stellio/search/model/AttributeInstance.kt
  search-service/src/test/kotlin/com/egm/stellio/search/web/EntityAccessControlHandlerTests.kt
  shared/src/main/kotlin/com/egm/stellio/shared/util/AuthUtils.kt
  shared/src/main/kotlin/com/egm/stellio/shared/util/JsonLdUtils.kt
Labels: fix

#830 feat(search): improve DB config for better performance
  search-service/src/main/kotlin/com/egm/stellio/search/service/AttributeInstanceService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/service/TemporalEntityAttributeService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/web/TemporalEntityHandler.kt
  search-service/src/main/resources/db/migration/V0_31__optimize_indices_attribute_instance.sql
  search-service/src/test/kotlin/com/egm/stellio/search/service/AttributeInstanceServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/service/TemporalEntityAttributeServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/web/TemporalEntityHandlerTests.kt
Labels: feature, search

#831 fix: apply the rule 6.3.5 on authz endpoint
  search-service/src/main/kotlin/com/egm/stellio/search/authorization/EnabledAuthorizationService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/authorization/EntityAccessRights.kt
  search-service/src/main/kotlin/com/egm/stellio/search/web/EntityAccessControlHandler.kt
  search-service/src/test/kotlin/com/egm/stellio/search/service/EntityPayloadServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/util/TestUtils.kt
  search-service/src/test/kotlin/com/egm/stellio/search/web/EntityAccessControlHandlerTests.kt
  shared/src/main/kotlin/com/egm/stellio/shared/util/AuthUtils.kt
Labels: fix
