Repository stellio-hub/stellio-context-broker, pull requests merged in 2023-02, with the labels that each got.

#854 chore: use our own build of json-merge lib
  build.gradle.kts
  search-service/build.gradle.kts
Labels: chore

#852 fix(authz): duplicate entities in `get authorized entities` when different rights through different groups
  search-service/src/main/kotlin/com/egm/stellio/search/authorization/EntityAccessRightsService.kt
  search-service/src/test/kotlin/com/egm/stellio/search/authorization/EntityAccessRightsServiceTests.kt
Labels: fix, authz

#857 chore(subscription): resize type column for entity info
  subscription-service/src/main/resources/db/migration/V0_17__resize_entity_info_type_column.sql
Labels: chore, subscription

#858 chore(devops): align services specific docker compose files with last version
  search-service/docker-compose.yml
  search-service/src/test/kotlin/com/egm/stellio/search/support/WithKafkaContainer.kt
  subscription-service/docker-compose.yml
Labels: chore, devops

#856 refactor: better SoC in core API services and query improvements
  search-service/config/detekt/baseline.xml
  search-service/src/main/kotlin/com/egm/stellio/search/authorization/AuthorizationService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/authorization/DisabledAuthorizationService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/authorization/EnabledAuthorizationService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/authorization/SubjectReferential.kt
  search-service/src/main/kotlin/com/egm/stellio/search/authorization/SubjectReferentialService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/listener/ObservationEventListener.kt
  search-service/src/main/kotlin/com/egm/stellio/search/model/AttributeInstance.kt
  search-service/src/main/kotlin/com/egm/stellio/search/model/EntityPayload.kt
  search-service/src/main/kotlin/com/egm/stellio/search/model/TemporalEntityAttribute.kt
  search-service/src/main/kotlin/com/egm/stellio/search/model/UpdateResult.kt
  search-service/src/main/kotlin/com/egm/stellio/search/service/AttributeInstanceService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/service/EntityAttributeCleanerService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/service/EntityOperationService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/service/EntityPayloadService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/service/IAMListener.kt
  search-service/src/main/kotlin/com/egm/stellio/search/service/QueryService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/service/SubscriptionEventListenerService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/service/TemporalEntityAttributeService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/support/ApiTestsBootstrapper.kt
  search-service/src/main/kotlin/com/egm/stellio/search/util/DBConversionUtils.kt
  search-service/src/main/kotlin/com/egm/stellio/search/web/EntityHandler.kt
  search-service/src/main/kotlin/com/egm/stellio/search/web/EntityOperationHandler.kt
  search-service/src/test/kotlin/com/egm/stellio/search/authorization/EnabledAuthorizationServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/authorization/EntityAccessRightsServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/authorization/SubjectInfoUtils.kt
  search-service/src/test/kotlin/com/egm/stellio/search/authorization/SubjectReferentialServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/listener/ObservationEventListenerTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/model/EntityModelTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/service/AttributeInstanceServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/service/AttributeServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/service/EntityEventServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/service/EntityOperationServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/service/EntityPayloadServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/service/EntityTypeServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/service/IAMListenerTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/service/QueryServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/service/SubscriptionEventListenerServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/service/TemporalEntityAttributeServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/service/TemporalEntityServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/util/ParameterizedTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/util/QueryParameterizedTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/util/TestUtils.kt
  search-service/src/test/kotlin/com/egm/stellio/search/web/EntityHandlerTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/web/EntityOperationHandlerTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/web/TemporalEntityHandlerTests.kt
  shared/src/testFixtures/kotlin/com/egm/stellio/shared/util/TestUtils.kt
Labels: refactoring, core

#843 feat(search): add enpoint create or update temporal representation of entity
  search-service/config/detekt/baseline.xml
  search-service/src/main/kotlin/com/egm/stellio/search/authorization/EntityAccessRights.kt
  search-service/src/main/kotlin/com/egm/stellio/search/model/AttributeInstance.kt
  search-service/src/main/kotlin/com/egm/stellio/search/service/AttributeInstanceService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/service/EntityOperationService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/service/EntityPayloadService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/service/TemporalEntityAttributeService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/web/EntityOperationHandler.kt
  search-service/src/main/kotlin/com/egm/stellio/search/web/TemporalEntityHandler.kt
  search-service/src/main/kotlin/db/migration/V0_29__JsonLd_migration.kt
  search-service/src/test/kotlin/com/egm/stellio/search/authorization/EnabledAuthorizationServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/service/AttributeInstanceServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/service/EntityOperationServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/service/QueryServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/service/SubscriptionEventListenerServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/service/TemporalEntityAttributeServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/web/EntityOperationHandlerTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/web/TemporalEntityHandlerTests.kt
  search-service/src/test/resources/ngsild/temporal/beehive_create_temporal_entity.jsonld
  search-service/src/test/resources/ngsild/temporal/beehive_create_temporal_entity_first_instance.jsonld
  search-service/src/test/resources/ngsild/temporal/beehive_create_temporal_entity_without_first_instance_expanded.jsonld
  search-service/src/test/resources/ngsild/temporal/beehive_update_temporal_entity.jsonld
  search-service/src/test/resources/ngsild/temporal/beehive_update_temporal_entity_without_mandatory_fields_expanded.jsonld
  search-service/src/test/resources/ngsild/temporal/invalid_beehive_create_temporal_entity.jsonld
  shared/src/main/kotlin/com/egm/stellio/shared/model/JsonLdEntity.kt
  shared/src/main/kotlin/com/egm/stellio/shared/model/NgsiLdEntity.kt
  shared/src/main/kotlin/com/egm/stellio/shared/util/ApiResponses.kt
  shared/src/main/kotlin/com/egm/stellio/shared/util/JsonLdUtils.kt
Labels: feature

#864 fix: add a check on idPattern info in subscriptions
  subscription-service/src/main/kotlin/com/egm/stellio/subscription/service/SubscriptionService.kt
  subscription-service/src/test/kotlin/com/egm/stellio/subscription/service/SubscriptionServiceTests.kt
Labels: fix

#839 feat(subscription): add common JSON-LD and HTTP behaviours
  .env
  docker-compose.yml
  search-service/src/main/kotlin/com/egm/stellio/search/service/TemporalEntityAttributeService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/util/DBQueryUtils.kt
  search-service/src/test/kotlin/com/egm/stellio/search/service/TemporalEntityAttributeServiceTests.kt
  shared/src/main/kotlin/com/egm/stellio/shared/util/JsonLdUtils.kt
  shared/src/main/kotlin/com/egm/stellio/shared/util/JsonUtils.kt
  shared/src/main/kotlin/com/egm/stellio/shared/util/QueryUtils.kt
  shared/src/test/kotlin/com/egm/stellio/shared/model/JsonLdEntityTests.kt
  shared/src/testFixtures/kotlin/com/egm/stellio/shared/util/AssertionUtils.kt
  shared/src/testFixtures/kotlin/com/egm/stellio/shared/util/JsonLdContextUtils.kt
  subscription-service/build.gradle.kts
  subscription-service/config/detekt/baseline.xml
  subscription-service/src/main/kotlin/com/egm/stellio/subscription/config/ApplicationProperties.kt
  subscription-service/src/main/kotlin/com/egm/stellio/subscription/firebase/FCMInitializer.kt
  subscription-service/src/main/kotlin/com/egm/stellio/subscription/firebase/FCMService.kt
  subscription-service/src/main/kotlin/com/egm/stellio/subscription/job/TimeIntervalNotificationJob.kt
  subscription-service/src/main/kotlin/com/egm/stellio/subscription/model/Endpoint.kt
  subscription-service/src/main/kotlin/com/egm/stellio/subscription/model/EntityInfo.kt
  subscription-service/src/main/kotlin/com/egm/stellio/subscription/model/NotificationParams.kt
  subscription-service/src/main/kotlin/com/egm/stellio/subscription/model/Subscription.kt
  subscription-service/src/main/kotlin/com/egm/stellio/subscription/repository/SubscriptionRepository.kt
  subscription-service/src/main/kotlin/com/egm/stellio/subscription/service/EntityEventListenerService.kt
  subscription-service/src/main/kotlin/com/egm/stellio/subscription/service/NotificationService.kt
  subscription-service/src/main/kotlin/com/egm/stellio/subscription/service/SubscriptionEventService.kt
  subscription-service/src/main/kotlin/com/egm/stellio/subscription/service/SubscriptionService.kt
  subscription-service/src/main/kotlin/com/egm/stellio/subscription/utils/DBConversionUtils.kt
  subscription-service/src/main/kotlin/com/egm/stellio/subscription/utils/DBQueryUtils.kt
  subscription-service/src/main/kotlin/com/egm/stellio/subscription/utils/ParsingUtils.kt
  subscription-service/src/main/kotlin/com/egm/stellio/subscription/utils/QueryUtils.kt
  subscription-service/src/main/kotlin/com/egm/stellio/subscription/web/SubscriptionHandler.kt
  subscription-service/src/main/resources/application.properties
  subscription-service/src/main/resources/db/migration/V0_18__add_contexts_attributes.sql
  subscription-service/src/test/kotlin/com/egm/stellio/subscription/job/TimeIntervalNotificationJobTest.kt
  subscription-service/src/test/kotlin/com/egm/stellio/subscription/model/SubscriptionTest.kt
  subscription-service/src/test/kotlin/com/egm/stellio/subscription/service/EntityEventListenerServiceTests.kt
  subscription-service/src/test/kotlin/com/egm/stellio/subscription/service/NotificationServiceTests.kt
  subscription-service/src/test/kotlin/com/egm/stellio/subscription/service/SubscriptionEventServiceTests.kt
  subscription-service/src/test/kotlin/com/egm/stellio/subscription/service/SubscriptionServiceTests.kt
  subscription-service/src/test/kotlin/com/egm/stellio/subscription/utils/FixtureUtils.kt
  subscription-service/src/test/kotlin/com/egm/stellio/subscription/utils/ParsingUtilsTests.kt
  subscription-service/src/test/kotlin/com/egm/stellio/subscription/web/SubscriptionHandlerTests.kt
  subscription-service/src/test/resources/logback-test.xml
  subscription-service/src/test/resources/ngsild/aquac/FeedingService.json
Labels: feature

#865 fix: check attribute existence by all reference or one
  search-service/src/main/kotlin/com/egm/stellio/search/service/AttributeInstanceService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/web/TemporalEntityHandler.kt
  search-service/src/test/kotlin/com/egm/stellio/search/service/AttributeInstanceServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/web/TemporalEntityHandlerTests.kt
  shared/src/main/kotlin/com/egm/stellio/shared/util/ApiResponses.kt
Labels: fix, temporal

#855 feat(common): remove costly compactions when sending entity events in Kafka
  search-service/config/detekt/baseline.xml
  search-service/src/main/kotlin/com/egm/stellio/search/listener/ObservationEventListener.kt
  search-service/src/main/kotlin/com/egm/stellio/search/service/EntityEventService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/web/EntityHandler.kt
  search-service/src/test/kotlin/com/egm/stellio/search/service/EntityEventServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/service/EntityPayloadServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/service/TemporalEntityAttributeServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/util/TestUtils.kt
  search-service/src/test/kotlin/com/egm/stellio/search/web/EntityHandlerTests.kt
  shared/src/main/kotlin/com/egm/stellio/shared/model/EntityEvent.kt
  shared/src/main/kotlin/com/egm/stellio/shared/util/JsonLdUtils.kt
  shared/src/test/kotlin/com/egm/stellio/shared/util/JsonUtilsTests.kt
  shared/src/testFixtures/resources/ngsild/events/entity/attributeAppendNumericPropDatasetIdEvent.json
  shared/src/testFixtures/resources/ngsild/events/entity/attributeAppendNumericPropEvent.json
  shared/src/testFixtures/resources/ngsild/events/entity/attributeAppendRelEvent.json
  shared/src/testFixtures/resources/ngsild/events/entity/attributeAppendTextPropEvent.json
  shared/src/testFixtures/resources/ngsild/events/entity/attributeAppendTypeEvent.json
  shared/src/testFixtures/resources/ngsild/events/entity/attributeDeleteAllInstancesEvent.json
  shared/src/testFixtures/resources/ngsild/events/entity/attributeDeleteEvent.json
  shared/src/testFixtures/resources/ngsild/events/entity/attributeReplaceNumericPropEvent.json
  shared/src/testFixtures/resources/ngsild/events/entity/attributeReplaceRelEvent.json
  shared/src/testFixtures/resources/ngsild/events/entity/attributeReplaceTextPropEvent.json
  shared/src/testFixtures/resources/ngsild/events/entity/attributeUpdateNumericPropDatasetIdEvent.json
  shared/src/testFixtures/resources/ngsild/events/entity/attributeUpdateNumericPropEvent.json
  shared/src/testFixtures/resources/ngsild/events/entity/attributeUpdateRelEvent.json
  shared/src/testFixtures/resources/ngsild/events/entity/attributeUpdateTextPropEvent.json
  shared/src/testFixtures/resources/ngsild/events/entity/entityCreateEvent.json
  shared/src/testFixtures/resources/ngsild/events/entity/entityDeleteEvent.json
  shared/src/testFixtures/resources/ngsild/events/entity/entityReplaceEvent.json
  shared/src/testFixtures/resources/ngsild/events/entity/entityUpdateEvent.json
  shared/src/testFixtures/resources/ngsild/events/entity/invalid/humidityAppendEvent.jsonld
  subscription-service/src/main/kotlin/com/egm/stellio/subscription/service/EntityEventListenerService.kt
  subscription-service/src/test/kotlin/com/egm/stellio/subscription/service/EntityEventListenerServiceTests.kt
Labels: feature

#868 fix(entity): add createdAt on all attributes of a newly created entity
  search-service/src/main/kotlin/com/egm/stellio/search/service/EntityPayloadService.kt
  shared/src/main/kotlin/com/egm/stellio/shared/model/JsonLdEntity.kt
Labels: fix, core
