Repository stellio-hub/stellio-context-broker, pull requests merged in 2023-03, with the labels that each got.

#869 feat: add support for NGSI-LD Query Language #683
  search-service/config/detekt/baseline.xml
  search-service/src/main/kotlin/com/egm/stellio/search/authorization/EnabledAuthorizationService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/service/EntityPayloadService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/service/QueryService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/service/TemporalEntityAttributeService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/util/TemporalQueryUtils.kt
  search-service/src/main/kotlin/com/egm/stellio/search/web/EntityAccessControlHandler.kt
  search-service/src/main/kotlin/com/egm/stellio/search/web/EntityHandler.kt
  search-service/src/main/kotlin/com/egm/stellio/search/web/TemporalEntityHandler.kt
  search-service/src/main/kotlin/com/egm/stellio/search/web/TemporalEntityOperationsHandler.kt
  search-service/src/test/kotlin/com/egm/stellio/search/authorization/EnabledAuthorizationServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/service/EntityQueryServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/service/QueryServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/service/TemporalEntityAttributeServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/util/TemporalQueryUtilsTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/web/TemporalEntityHandlerTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/web/TemporalEntityOperationsHandlerTests.kt
  search-service/src/test/resources/ngsild/entity_with_all_attributes_1.jsonld
  search-service/src/test/resources/ngsild/entity_with_all_attributes_2.jsonld
  shared/config/detekt/baseline.xml
  shared/src/main/kotlin/com/egm/stellio/shared/util/ApiUtils.kt
  shared/src/main/kotlin/com/egm/stellio/shared/util/GeoQueryUtils.kt
  shared/src/main/kotlin/com/egm/stellio/shared/util/JsonLdUtils.kt
  shared/src/main/kotlin/com/egm/stellio/shared/util/QueryUtils.kt
  shared/src/main/kotlin/com/egm/stellio/shared/util/UriUtils.kt
  shared/src/test/kotlin/com/egm/stellio/shared/util/ApiUtilsTests.kt
  shared/src/test/kotlin/com/egm/stellio/shared/util/GeoQueryUtilsTests.kt
  shared/src/test/kotlin/com/egm/stellio/shared/util/JsonLdUtilsTests.kt
  shared/src/testFixtures/kotlin/com/egm/stellio/shared/util/TestUtils.kt
  subscription-service/src/main/kotlin/com/egm/stellio/subscription/service/NotificationService.kt
  subscription-service/src/main/kotlin/com/egm/stellio/subscription/service/SubscriptionService.kt
  subscription-service/src/main/kotlin/com/egm/stellio/subscription/utils/QueryUtils.kt
  subscription-service/src/main/kotlin/com/egm/stellio/subscription/web/SubscriptionHandler.kt
  subscription-service/src/test/kotlin/com/egm/stellio/subscription/service/NotificationServiceTests.kt
  subscription-service/src/test/kotlin/com/egm/stellio/subscription/service/SubscriptionServiceTests.kt
Labels: feature

#876 feat(search): implement Delete Temporal Representation of an Entity endpoint
  search-service/src/main/kotlin/com/egm/stellio/search/web/TemporalEntityHandler.kt
  search-service/src/test/kotlin/com/egm/stellio/search/web/TemporalEntityHandlerTests.kt
Labels: feature

#881 feature: implement delete attribute temporal
  search-service/src/main/kotlin/com/egm/stellio/search/web/TemporalEntityHandler.kt
  search-service/src/test/kotlin/com/egm/stellio/search/web/TemporalEntityHandlerTests.kt
Labels: feature, temporal

#885 feat: check Link header format
  search-service/src/main/kotlin/com/egm/stellio/search/web/AttributeHandler.kt
  search-service/src/main/kotlin/com/egm/stellio/search/web/EntityAccessControlHandler.kt
  search-service/src/main/kotlin/com/egm/stellio/search/web/EntityHandler.kt
  search-service/src/main/kotlin/com/egm/stellio/search/web/EntityOperationHandler.kt
  search-service/src/main/kotlin/com/egm/stellio/search/web/EntityTypeHandler.kt
  search-service/src/main/kotlin/com/egm/stellio/search/web/TemporalEntityHandler.kt
  search-service/src/main/kotlin/com/egm/stellio/search/web/TemporalEntityOperationsHandler.kt
  search-service/src/test/kotlin/com/egm/stellio/search/web/EntityHandlerTests.kt
  shared/src/main/kotlin/com/egm/stellio/shared/util/ApiUtils.kt
  shared/src/test/kotlin/com/egm/stellio/shared/util/ApiUtilsTests.kt
  subscription-service/src/main/kotlin/com/egm/stellio/subscription/web/SubscriptionHandler.kt
Labels: feature

#894 feat: implement Entity Type selection language for Core and Temporal API
  search-service/config/detekt/baseline.xml
  search-service/src/main/kotlin/com/egm/stellio/search/authorization/EnabledAuthorizationService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/authorization/EntityAccessRightsService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/service/EntityPayloadService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/util/TemporalQueryUtils.kt
  search-service/src/main/kotlin/com/egm/stellio/search/web/EntityHandler.kt
  search-service/src/test/kotlin/com/egm/stellio/search/authorization/EnabledAuthorizationServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/authorization/EntityAccessRightsServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/service/EntityQueryServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/service/QueryServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/util/TemporalQueryUtilsTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/web/EntityHandlerTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/web/TemporalEntityHandlerTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/web/TemporalEntityOperationsHandlerTests.kt
  search-service/src/test/resources/ngsild/apiary.jsonld
  search-service/src/test/resources/ngsild/beekeeper.jsonld
  search-service/src/test/resources/ngsild/entity_with_multi_types.jsonld
  shared/src/main/kotlin/com/egm/stellio/shared/model/QueryParams.kt
  shared/src/main/kotlin/com/egm/stellio/shared/util/ApiUtils.kt
  shared/src/main/kotlin/com/egm/stellio/shared/util/QueryUtils.kt
  shared/src/test/kotlin/com/egm/stellio/shared/util/ApiUtilsTests.kt
  shared/src/testFixtures/kotlin/com/egm/stellio/shared/util/JsonLdContextUtils.kt
Labels: feature, core, temporal, ngsild-1.5.1

#886 feat: add support NGSI-LD GeoQuery language (#684)
  search-service/src/main/kotlin/com/egm/stellio/search/service/EntityPayloadService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/service/QueryService.kt
  search-service/src/test/kotlin/com/egm/stellio/search/service/EntityQueryServiceTests.kt
  search-service/src/test/resources/ngsild/entity_with_all_attributes_1.jsonld
  search-service/src/test/resources/ngsild/entity_with_all_attributes_2.jsonld
  shared/src/main/kotlin/com/egm/stellio/shared/util/JsonLdUtils.kt
Labels: feature, core, temporal

#882 feat: implement modify attribute instance in temporal representation …
  search-service/config/detekt/baseline.xml
  search-service/src/main/kotlin/com/egm/stellio/search/model/AttributeInstance.kt
  search-service/src/main/kotlin/com/egm/stellio/search/service/AttributeInstanceService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/web/TemporalEntityHandler.kt
  search-service/src/test/kotlin/com/egm/stellio/search/service/AttributeInstanceServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/web/TemporalEntityHandlerTests.kt
  search-service/src/test/resources/ngsild/fragments/temporal_instance_fragment.jsonld
  shared/src/main/kotlin/com/egm/stellio/shared/model/NgsiLdEntity.kt
  shared/src/main/kotlin/com/egm/stellio/shared/util/JsonLdUtils.kt
Labels: feature

#898 fix: retrieve global roles transitively
  search-service/src/main/kotlin/com/egm/stellio/search/authorization/EnabledAuthorizationService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/authorization/EntityAccessRightsService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/authorization/SubjectReferentialService.kt
  search-service/src/test/kotlin/com/egm/stellio/search/authorization/EnabledAuthorizationServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/authorization/EntityAccessRightsServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/authorization/SubjectReferentialServiceTests.kt
Labels: fix
