Repository stellio-hub/stellio-context-broker, pull requests merged in 2023-04, with the labels that each got.

#907 feat: upgrade to Gradle 8.0.x
  build.gradle.kts
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: feature, devops

#903 fix(temporal): inconsistent values for instanceId between specific column and instance payload
  search-service/config/detekt/baseline.xml
  search-service/src/main/kotlin/com/egm/stellio/search/model/AttributeInstance.kt
  search-service/src/main/kotlin/com/egm/stellio/search/service/AttributeInstanceService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/service/SubscriptionEventListenerService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/service/TemporalEntityAttributeService.kt
  search-service/src/main/resources/db/migration/V0_32__fix_instance_id_difference_in_its_column_and_payload.sql
  search-service/src/test/kotlin/com/egm/stellio/search/service/AttributeInstanceServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/support/BusinessObjectsFactory.kt
Labels: fix

#912 feat(common): check for supported entity content (4.6.4)
  search-service/src/main/kotlin/com/egm/stellio/search/web/EntityHandler.kt
  search-service/src/main/kotlin/com/egm/stellio/search/web/EntityOperationHandler.kt
  search-service/src/main/kotlin/com/egm/stellio/search/web/TemporalEntityHandler.kt
  shared/src/main/kotlin/com/egm/stellio/shared/util/ApiResponses.kt
  shared/src/main/kotlin/com/egm/stellio/shared/util/DataRepresentationUtils.kt
  shared/src/main/kotlin/com/egm/stellio/shared/util/JsonUtils.kt
  shared/src/test/kotlin/com/egm/stellio/shared/util/DataRepresentationUtilsTests.kt
Labels: feature, common

#909 fix(core): queries with only a `q` request parameter were failing with a 500
  search-service/src/main/kotlin/com/egm/stellio/search/service/EntityPayloadService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/util/DBQueryUtils.kt
  search-service/src/test/kotlin/com/egm/stellio/search/service/EntityQueryServiceTests.kt
  search-service/src/test/resources/ngsild/apiary.jsonld
  search-service/src/test/resources/ngsild/beekeeper.jsonld
Labels: fix

#861 conf: integrate CodeQL scanning action
  .github/workflows/codeql.yml
Labels: fix, quality

#921 fix: entities payloads that don't have the types column filled
  search-service/src/main/resources/db/migration/V0_33__fix_entities_payloads_that_don't_have_the_types_column_filled.sql
Labels: fix
