Repository stellio-hub/stellio-context-broker, pull requests merged in 2023-07, with the labels that each got.

#847 feat: add GH action for Anchore vulnerability scan
  .github/workflows/anchore.yml
  .grype.yaml
Labels: feature

#947 feat: implement merge entity endpoint - 6.5.3.4
  search-service/config/detekt/baseline.xml
  search-service/src/main/kotlin/com/egm/stellio/search/service/EntityPayloadService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/service/TemporalEntityAttributeService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/util/AttributeInstanceUtils.kt
  search-service/src/main/kotlin/com/egm/stellio/search/web/EntityHandler.kt
  search-service/src/test/kotlin/com/egm/stellio/search/authorization/EntityAccessRightsServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/service/EntityPayloadServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/service/QueryServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/service/TemporalEntityAttributeServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/util/AttributeInstanceUtilsTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/web/EntityHandlerTests.kt
  search-service/src/test/resources/ngsild/aquac/fragments/DeadFishes_mergeEntity.json
  search-service/src/test/resources/ngsild/fragments/beehive_mergeAttribute.json
  search-service/src/test/resources/ngsild/fragments/beehive_mergeAttribute_without_observedAt.json
  search-service/src/test/resources/ngsild/fragments/beehive_mergeAttributes.json
  shared/src/main/kotlin/com/egm/stellio/shared/model/NgsiLdEntity.kt
  shared/src/main/kotlin/com/egm/stellio/shared/util/ApiUtils.kt
  shared/src/test/kotlin/com/egm/stellio/shared/util/JsonLdUtilsTests.kt
  subscription-service/src/main/kotlin/com/egm/stellio/subscription/model/Subscription.kt
  subscription-service/src/main/kotlin/com/egm/stellio/subscription/service/SubscriptionService.kt
Labels: feature

#958 chore: upgrade to Timescale 2.11.1
  docker-compose.yml
  kubernetes/postgres-deployment.yaml
  search-service/docker-compose.yml
  search-service/src/test/kotlin/com/egm/stellio/search/support/WithTimescaleContainer.kt
  subscription-service/docker-compose.yml
  subscription-service/src/test/kotlin/com/egm/stellio/subscription/support/WithTimescaleContainer.kt
Labels: chore

#968 feat(core): improve entity delete process
  search-service/src/main/kotlin/com/egm/stellio/search/service/AttributeInstanceService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/service/EntityAttributeCleanerService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/service/EntityOperationService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/service/EntityPayloadService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/service/TemporalEntityAttributeService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/web/EntityHandler.kt
  search-service/src/main/kotlin/com/egm/stellio/search/web/TemporalEntityHandler.kt
  search-service/src/test/kotlin/com/egm/stellio/search/service/AttributeInstanceServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/service/EntityOperationServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/service/EntityPayloadServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/service/EntityQueryServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/web/EntityHandlerTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/web/TemporalEntityHandlerTests.kt
Labels: feature

#969 fix(tenant): postgis functions are not visible from tenants schemas
  search-service/src/main/kotlin/com/egm/stellio/search/service/AttributeInstanceService.kt
  search-service/src/main/kotlin/db/migration/V0_29__JsonLd_migration.kt
  shared/src/main/kotlin/com/egm/stellio/shared/util/GeoQueryUtils.kt
  shared/src/test/kotlin/com/egm/stellio/shared/util/GeoQueryUtilsTests.kt
  subscription-service/src/main/kotlin/com/egm/stellio/subscription/service/SubscriptionService.kt
Labels: fix
