Repository stellio-hub/stellio-context-broker, pull requests merged in 2024-04, with the labels that each got.

#1134 fix(core): entities core members are not processed in batch operations
  search-service/src/main/kotlin/com/egm/stellio/search/service/EntityOperationService.kt
  search-service/src/test/kotlin/com/egm/stellio/search/service/EntityPayloadServiceTests.kt
  shared/src/main/kotlin/com/egm/stellio/shared/model/ExpandedEntity.kt
Labels: fix, core

#1139 fix: add core context if missing in batch operations
  search-service/src/main/kotlin/com/egm/stellio/search/web/EntityOperationHandler.kt
  shared/src/main/kotlin/com/egm/stellio/shared/util/ApiUtils.kt
Labels: fix, core

#1140 fix(authz): incorrect handling of multi-types in get subject access rights
  search-service/src/main/kotlin/com/egm/stellio/search/authorization/EntityAccessRightsService.kt
  search-service/src/test/kotlin/com/egm/stellio/search/authorization/EntityAccessRightsServiceTests.kt
Labels: fix, authz

#1142 fix: error code when requesting a pagination limit that surpasses the configured value
  .env
  docker-compose.yml
  search-service/src/test/kotlin/com/egm/stellio/search/web/EntityHandlerTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/web/TemporalEntityHandlerTests.kt
  shared/src/main/kotlin/com/egm/stellio/shared/model/ErrorResponse.kt
  shared/src/main/kotlin/com/egm/stellio/shared/util/ApiResponses.kt
  shared/src/main/kotlin/com/egm/stellio/shared/util/ApiUtils.kt
  subscription-service/src/test/kotlin/com/egm/stellio/subscription/web/SubscriptionHandlerTests.kt
Labels: fix, core

#1120 feat(core): add support for LanguageProperty
  search-service/config/detekt/baseline.xml
  search-service/src/main/kotlin/com/egm/stellio/search/model/EntityTypeInfo.kt
  search-service/src/main/kotlin/com/egm/stellio/search/model/Query.kt
  search-service/src/main/kotlin/com/egm/stellio/search/model/TemporalEntityAttribute.kt
  search-service/src/main/kotlin/com/egm/stellio/search/service/TemporalEntityAttributeService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/util/AttributeInstanceUtils.kt
  search-service/src/main/kotlin/com/egm/stellio/search/util/EntitiesQueryUtils.kt
  search-service/src/main/kotlin/com/egm/stellio/search/util/TemporalEntityBuilder.kt
  search-service/src/main/kotlin/com/egm/stellio/search/web/EntityOperationHandler.kt
  search-service/src/main/kotlin/com/egm/stellio/search/web/TemporalEntityOperationsHandler.kt
  search-service/src/main/kotlin/db/migration/V0_29__JsonLd_migration.kt
  search-service/src/test/kotlin/com/egm/stellio/search/scope/ScopeServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/service/AttributeInstanceServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/service/EntityTypeServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/service/TemporalEntityAttributeServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/support/BusinessObjectsFactory.kt
  search-service/src/test/kotlin/com/egm/stellio/search/support/TestUtils.kt
  search-service/src/test/kotlin/com/egm/stellio/search/util/EntitiesQueryUtilsTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/util/PatchAttributeTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/util/TemporalEntityParameterizedSource.kt
  search-service/src/test/resources/ngsild/expectations/beehive_language_property_temporal_values.jsonld
  search-service/src/test/resources/ngsild/fragments/temporal_instance_language_fragment.jsonld
  shared/src/main/kotlin/com/egm/stellio/shared/model/CompactedEntity.kt
  shared/src/main/kotlin/com/egm/stellio/shared/model/NgsiLdDataRepresentation.kt
  shared/src/main/kotlin/com/egm/stellio/shared/model/NgsiLdEntity.kt
  shared/src/main/kotlin/com/egm/stellio/shared/util/ApiUtils.kt
  shared/src/main/kotlin/com/egm/stellio/shared/util/JsonLdUtils.kt
  shared/src/test/kotlin/com/egm/stellio/shared/model/CompactedEntityTests.kt
  shared/src/test/kotlin/com/egm/stellio/shared/model/LanguageFilterTests.kt
  shared/src/test/kotlin/com/egm/stellio/shared/model/NgsiLdEntityTests.kt
  shared/src/testFixtures/kotlin/com/egm/stellio/shared/util/JsonLdContextUtils.kt
  shared/src/testFixtures/resources/jsonld-contexts/apic.jsonld
  subscription-service/src/main/kotlin/com/egm/stellio/subscription/model/Subscription.kt
  subscription-service/src/main/kotlin/com/egm/stellio/subscription/service/NotificationService.kt
  subscription-service/src/main/kotlin/com/egm/stellio/subscription/service/SubscriptionService.kt
  subscription-service/src/main/resources/db/migration/V0_28__add_lang_column.sql
  subscription-service/src/test/kotlin/com/egm/stellio/subscription/service/NotificationServiceTests.kt
  subscription-service/src/test/kotlin/com/egm/stellio/subscription/service/SubscriptionServiceTests.kt
  subscription-service/src/test/resources/ngsild/subscription_full.json
Labels: feature, core, ngsild-1.4.1

#1145 fix(authz): avoid core context duplications in authz API
  shared/src/main/kotlin/com/egm/stellio/shared/util/ApiUtils.kt
  shared/src/main/kotlin/com/egm/stellio/shared/util/AuthUtils.kt
Labels: fix, authz

#1146 feat(core): align behavior for update entity attributes (1.6+ compliance)
  search-service/src/main/kotlin/com/egm/stellio/search/service/TemporalEntityAttributeService.kt
Labels: feature, core, ngsild-1.6.1

#1147 refactor: remove contexts from expanded entity representation
  search-service/src/main/kotlin/com/egm/stellio/search/authorization/EnabledAuthorizationService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/service/QueryService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/util/TemporalEntityBuilder.kt
  search-service/src/main/kotlin/com/egm/stellio/search/web/EntityHandler.kt
  search-service/src/main/kotlin/com/egm/stellio/search/web/TemporalEntityHandler.kt
  search-service/src/main/kotlin/db/migration/V0_29__JsonLd_migration.kt
  search-service/src/test/kotlin/com/egm/stellio/search/service/QueryServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/util/TemporalEntityBuilderTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/web/EntityAccessControlHandlerTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/web/EntityHandlerTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/web/EntityOperationHandlerTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/web/TemporalEntityHandlerTests.kt
  shared/src/main/kotlin/com/egm/stellio/shared/model/ExpandedEntity.kt
  shared/src/main/kotlin/com/egm/stellio/shared/util/JsonLdUtils.kt
  shared/src/test/kotlin/com/egm/stellio/shared/model/ExpandedEntityTests.kt
  subscription-service/src/main/kotlin/com/egm/stellio/subscription/listener/EntityEventListenerService.kt
  subscription-service/src/main/kotlin/com/egm/stellio/subscription/service/NotificationService.kt
Labels: refactoring, core

#1148 feat: remove external depedencies in tests
  search-service/src/main/kotlin/com/egm/stellio/search/web/AttributeHandler.kt
  search-service/src/main/kotlin/com/egm/stellio/search/web/EntityAccessControlHandler.kt
  search-service/src/main/kotlin/com/egm/stellio/search/web/EntityHandler.kt
  search-service/src/main/kotlin/com/egm/stellio/search/web/EntityOperationHandler.kt
  search-service/src/main/kotlin/com/egm/stellio/search/web/EntityTypeHandler.kt
  search-service/src/main/kotlin/com/egm/stellio/search/web/TemporalEntityHandler.kt
  search-service/src/main/kotlin/com/egm/stellio/search/web/TemporalEntityOperationsHandler.kt
  search-service/src/test/kotlin/com/egm/stellio/search/authorization/AuthUtilsTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/authorization/AuthorizationServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/config/WebSecurityTestConfig.kt
  search-service/src/test/kotlin/com/egm/stellio/search/web/AnonymousUserHandlerTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/web/AttributeHandlerTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/web/EntityAccessControlHandlerTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/web/EntityHandlerTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/web/EntityOperationHandlerTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/web/EntityTypeHandlerTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/web/TemporalEntityHandlerTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/web/TemporalEntityOperationsHandlerTests.kt
  search-service/src/test/resources/application-test.properties
  shared/src/main/kotlin/com/egm/stellio/shared/config/ApplicationProperties.kt
  shared/src/main/kotlin/com/egm/stellio/shared/config/TenantAuthenticationManagerResolver.kt
  shared/src/main/kotlin/com/egm/stellio/shared/config/WebSecurityConfig.kt
  shared/src/main/kotlin/com/egm/stellio/shared/util/ApiUtils.kt
  shared/src/main/kotlin/com/egm/stellio/shared/util/AuthUtils.kt
  shared/src/main/kotlin/com/egm/stellio/shared/util/JsonLdUtils.kt
  shared/src/main/resources/shared.properties
  shared/src/test/kotlin/com/egm/stellio/shared/util/ApiUtilsTests.kt
  shared/src/test/kotlin/com/egm/stellio/shared/web/TenantWebFilterTests.kt
  subscription-service/src/main/kotlin/com/egm/stellio/subscription/web/SubscriptionHandler.kt
  subscription-service/src/test/resources/application-test.properties
Labels: feature
