Repository stellio-hub/stellio-context-broker, pull requests merged in 2024-03, with the labels that each got.

#1114 fix(core): cast to geography type fails in non default tenants
  shared/src/main/kotlin/com/egm/stellio/shared/util/GeoQueryUtils.kt
  shared/src/test/kotlin/com/egm/stellio/shared/util/GeoQueryUtilsTests.kt
Labels: fix, core

#1112 feature(core): update simplified representation in multi-attribute case with dataset
  shared/config/detekt/baseline.xml
  shared/src/main/kotlin/com/egm/stellio/shared/model/CompactedEntity.kt
  shared/src/main/kotlin/com/egm/stellio/shared/util/JsonLdUtils.kt
  shared/src/test/kotlin/com/egm/stellio/shared/model/CompactedEntityTests.kt
  shared/src/test/kotlin/com/egm/stellio/shared/model/ExpandedEntityTests.kt
Labels: feature, core

#1115 fix(core): do not force existing types to be present in payload when updating or appending types
  search-service/src/main/kotlin/com/egm/stellio/search/service/EntityPayloadService.kt
  search-service/src/test/kotlin/com/egm/stellio/search/service/EntityPayloadServiceTests.kt
Labels: fix, core

#1098 feat(subscription): add support for sysAttrs to notification params
  subscription-service/src/main/kotlin/com/egm/stellio/subscription/model/NotificationParams.kt
  subscription-service/src/main/kotlin/com/egm/stellio/subscription/service/NotificationService.kt
  subscription-service/src/main/kotlin/com/egm/stellio/subscription/service/SubscriptionService.kt
  subscription-service/src/main/resources/db/migration/V0_27__add_sysAttrs_column.sql
  subscription-service/src/test/kotlin/com/egm/stellio/subscription/service/NotificationServiceTests.kt
  subscription-service/src/test/kotlin/com/egm/stellio/subscription/service/SubscriptionServiceTests.kt
  subscription-service/src/test/resources/ngsild/subscription_full.json
Labels: feature, subscription

#1122 fix(temporal): prefix timescale functions (when called from non default tenant)
  search-service/src/main/kotlin/com/egm/stellio/search/scope/ScopeService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/service/AttributeInstanceService.kt
Labels: fix, temporal
