Repository stellio-hub/stellio-context-broker, pull requests merged in 2024-08, with the labels that each got.

#1211 fix(core): error sending Kafka events for batch operations when many times the same entity id
  search-service/config/detekt/baseline.xml
  search-service/src/main/kotlin/com/egm/stellio/search/service/EntityOperationService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/web/EntityOperationHandler.kt
  search-service/src/test/kotlin/com/egm/stellio/search/service/EntityOperationServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/web/EntityOperationHandlerTests.kt
Labels: fix

#1208 feat: propagate an user's deleted entities to Kafka
  search-service/src/main/kotlin/com/egm/stellio/search/listener/IAMListener.kt
  search-service/src/main/kotlin/com/egm/stellio/search/service/EntityPayloadService.kt
  search-service/src/test/kotlin/com/egm/stellio/search/listener/IAMListenerTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/service/EntityOperationServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/service/EntityPayloadServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/web/EntityHandlerTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/web/TemporalEntityHandlerTests.kt
Labels: feature

#1129 feat: upgrade Timescale and Kafka
  config/kafka/update_run.sh
  docker-compose.yml
  search-service/docker-compose.yml
  search-service/src/test/kotlin/com/egm/stellio/search/support/WithKafkaContainer.kt
  search-service/src/test/kotlin/com/egm/stellio/search/support/WithTimescaleContainer.kt
  subscription-service/docker-compose.yml
  subscription-service/src/test/kotlin/com/egm/stellio/subscription/support/WithKafkaContainer.kt
  subscription-service/src/test/kotlin/com/egm/stellio/subscription/support/WithTimescaleContainer.kt
Labels: chore, devops

#1209 feat: docker-compose v2
  README.md
  docker-compose.yml
Labels: feature

#1220 fix: interval bounds in temporal queries
  search-service/src/main/kotlin/com/egm/stellio/search/scope/ScopeService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/service/AttributeInstanceService.kt
  search-service/src/test/kotlin/com/egm/stellio/search/scope/ScopeServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/service/AttributeInstanceServiceTests.kt
Labels: fix, temporal

#1227 fix: simple quotes escape in queries
  search-service/src/test/kotlin/com/egm/stellio/search/entity/service/EntityServiceQueriesTests.kt
  search-service/src/test/resources/ngsild/entity_with_all_attributes_1.jsonld
  search-service/src/test/resources/ngsild/entity_with_all_attributes_2.jsonld
  shared/src/main/kotlin/com/egm/stellio/shared/util/QueryUtils.kt
  subscription-service/src/test/kotlin/com/egm/stellio/subscription/service/SubscriptionServiceTests.kt
Labels: fix, core

#1222 chore: redo and clean all indexes on attributes instances tables
  search-service/src/main/resources/db/migration/V0_42__fix_indexes_in_hypertables.sql
Labels: feature
