Repository stellio-hub/stellio-context-broker, pull requests merged in 2024-12, with the labels that each got.

#1275 chore: upgrade Kotlin 2.1 / fix deprecations and upgrades
  api-gateway/src/main/resources/application.yml
  build.gradle.kts
  search-service/config/detekt/baseline.xml
  search-service/src/main/kotlin/com/egm/stellio/search/csr/model/NGSILDWarning.kt
  search-service/src/test/kotlin/com/egm/stellio/search/support/BusinessObjectsFactory.kt
  search-service/src/test/kotlin/com/egm/stellio/search/temporal/service/AggregatedTemporalQueryServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/temporal/service/AttributeInstanceServiceTests.kt
  shared/config/detekt/baseline.xml
  shared/src/main/resources/shared.properties
  subscription-service/src/test/kotlin/com/egm/stellio/subscription/support/WithKafkaContainer.kt
Labels: chore

#1274 feat: add language filter to sub attributes
  shared/src/main/kotlin/com/egm/stellio/shared/model/CompactedEntity.kt
  shared/src/main/kotlin/com/egm/stellio/shared/util/JsonLdUtils.kt
  shared/src/test/kotlin/com/egm/stellio/shared/model/LanguageFilterTests.kt
Labels: feature, core

#1271 feat(common): return an `InvalidRequest` error when a parameter is invalid - 6.3.20
  build.gradle.kts
  config/detekt/detekt.yml
  search-service/config/detekt/baseline.xml
  search-service/src/main/kotlin/com/egm/stellio/search/authorization/service/EntityAccessRightsService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/authorization/web/EntityAccessControlHandler.kt
  search-service/src/main/kotlin/com/egm/stellio/search/csr/service/ContextSourceCaller.kt
  search-service/src/main/kotlin/com/egm/stellio/search/csr/web/ContextSourceRegistrationHandler.kt
  search-service/src/main/kotlin/com/egm/stellio/search/discovery/web/AttributeHandler.kt
  search-service/src/main/kotlin/com/egm/stellio/search/discovery/web/EntityTypeHandler.kt
  search-service/src/main/kotlin/com/egm/stellio/search/entity/model/EntitiesQuery.kt
  search-service/src/main/kotlin/com/egm/stellio/search/entity/service/EntityQueryService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/entity/service/LinkedEntityService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/entity/util/EntitiesQueryUtils.kt
  search-service/src/main/kotlin/com/egm/stellio/search/entity/web/EntityHandler.kt
  search-service/src/main/kotlin/com/egm/stellio/search/entity/web/EntityOperationHandler.kt
  search-service/src/main/kotlin/com/egm/stellio/search/temporal/util/TemporalQueryParamsUtils.kt
  search-service/src/main/kotlin/com/egm/stellio/search/temporal/util/TemporalQueryUtils.kt
  search-service/src/main/kotlin/com/egm/stellio/search/temporal/web/TemporalApiResponses.kt
  search-service/src/main/kotlin/com/egm/stellio/search/temporal/web/TemporalEntityHandler.kt
  search-service/src/main/kotlin/com/egm/stellio/search/temporal/web/TemporalEntityOperationsHandler.kt
  search-service/src/test/kotlin/com/egm/stellio/search/authorization/service/AuthorizationServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/authorization/service/EnabledAuthorizationServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/authorization/service/EntityAccessRightsServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/csr/service/ContextSourceCallerTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/entity/service/EntityServiceQueriesTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/entity/service/LinkedEntityServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/entity/util/EntitiesQueryUtilsTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/entity/web/EntityHandlerTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/scope/ScopeServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/support/BusinessObjectsFactory.kt
  search-service/src/test/kotlin/com/egm/stellio/search/temporal/service/TemporalPaginationServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/temporal/service/TemporalQueryServiceTests.kt
  shared/src/main/kotlin/com/egm/stellio/shared/model/CompactedEntity.kt
  shared/src/main/kotlin/com/egm/stellio/shared/model/GeoQuery.kt
  shared/src/main/kotlin/com/egm/stellio/shared/model/LinkedEntityQuery.kt
  shared/src/main/kotlin/com/egm/stellio/shared/model/NgsiLdDataRepresentation.kt
  shared/src/main/kotlin/com/egm/stellio/shared/model/PaginationQuery.kt
  shared/src/main/kotlin/com/egm/stellio/shared/queryparameter/AllowedParameters.kt
  shared/src/main/kotlin/com/egm/stellio/shared/queryparameter/GeoQuery.kt
  shared/src/main/kotlin/com/egm/stellio/shared/queryparameter/Georel.kt
  shared/src/main/kotlin/com/egm/stellio/shared/queryparameter/LinkedEntityQuery.kt
  shared/src/main/kotlin/com/egm/stellio/shared/queryparameter/OptionsValue.kt
  shared/src/main/kotlin/com/egm/stellio/shared/queryparameter/PaginationQuery.kt
  shared/src/main/kotlin/com/egm/stellio/shared/queryparameter/QueryParameter.kt
  shared/src/main/kotlin/com/egm/stellio/shared/util/ApiResponses.kt
  shared/src/main/kotlin/com/egm/stellio/shared/util/ApiUtils.kt
  shared/src/main/kotlin/com/egm/stellio/shared/util/GeoQueryUtils.kt
  shared/src/main/kotlin/com/egm/stellio/shared/util/GeoUtils.kt
  shared/src/main/kotlin/com/egm/stellio/shared/util/LinkedEntityQueryUtils.kt
  shared/src/main/kotlin/com/egm/stellio/shared/web/ExceptionHandler.kt
  shared/src/test/kotlin/com/egm/stellio/shared/model/ExpandedEntityTests.kt
  shared/src/test/kotlin/com/egm/stellio/shared/util/ApiUtilsTests.kt
  shared/src/test/kotlin/com/egm/stellio/shared/util/GeoQueryUtilsTests.kt
  subscription-service/src/main/kotlin/com/egm/stellio/subscription/job/TimeIntervalNotificationJob.kt
  subscription-service/src/main/kotlin/com/egm/stellio/subscription/model/GeoQ.kt
  subscription-service/src/main/kotlin/com/egm/stellio/subscription/service/SubscriptionService.kt
  subscription-service/src/main/kotlin/com/egm/stellio/subscription/web/SubscriptionHandler.kt
Labels: feature, common

#1284 fix: allows to check existence of an attribute whatever its datasetId
  search-service/src/main/kotlin/com/egm/stellio/search/entity/service/EntityAttributeService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/entity/service/EntityService.kt
  search-service/src/test/kotlin/com/egm/stellio/search/entity/service/EntityAttributeServiceTests.kt
Labels: fix

#1282 context source implementation for query entities
  search-service/config/detekt/baseline.xml
  search-service/src/main/kotlin/com/egm/stellio/search/csr/model/CSRFilters.kt
  search-service/src/main/kotlin/com/egm/stellio/search/csr/model/ContextSourceRegistration.kt
  search-service/src/main/kotlin/com/egm/stellio/search/csr/service/ContextSourceCaller.kt
  search-service/src/main/kotlin/com/egm/stellio/search/csr/service/ContextSourceRegistrationService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/csr/service/ContextSourceUtils.kt
  search-service/src/main/kotlin/com/egm/stellio/search/entity/web/EntityHandler.kt
  search-service/src/test/kotlin/com/egm/stellio/search/csr/service/ContextSourceCallerTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/csr/service/ContextSourceRegistrationServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/csr/service/ContextSourceUtilsTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/entity/web/EntityHandlerTests.kt
  search-service/src/test/resources/ngsild/csr/contextSourceRegistration_minimal_entities.json
  shared/src/main/kotlin/com/egm/stellio/shared/util/QueryUtils.kt
  subscription-service/src/main/kotlin/com/egm/stellio/subscription/service/SubscriptionService.kt
Labels: feature, ngsild-1.6.1, csr

#1291 chore: migrate deprecated and no longer working JSON path checks
  search-service/src/test/kotlin/com/egm/stellio/search/authorization/web/EntityAccessControlHandlerTests.kt
Labels: chore, authz

#1290 fix: incorrect behaviors in Batch Entity Upsert endpoint
  search-service/src/main/kotlin/com/egm/stellio/search/entity/service/EntityOperationService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/entity/web/BatchAPIResponses.kt
  search-service/src/main/kotlin/com/egm/stellio/search/entity/web/EntityOperationHandler.kt
  search-service/src/test/kotlin/com/egm/stellio/search/entity/service/EntityOperationServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/entity/web/EntityOperationHandlerTests.kt
  shared/src/main/kotlin/com/egm/stellio/shared/queryparameter/OptionsValue.kt
Labels: fix, core

#1289 feat: add a default SQL view for easy Grafana querying
  search-service/src/main/resources/db/migration/V0_44__add_view_for_grafana_querying.sql
Labels: feature
