Repository stellio-hub/stellio-context-broker, pull requests merged in 2024-05, with the labels that each got.

#1149 feat: merge service account id to subject id
  search-service/src/main/kotlin/com/egm/stellio/search/authorization/EntityAccessRightsService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/authorization/SubjectReferential.kt
  search-service/src/main/kotlin/com/egm/stellio/search/authorization/SubjectReferentialService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/listener/IAMListener.kt
  search-service/src/main/resources/db/migration/V0_40__migrate_service_account_to_subject_column.sql
  search-service/src/test/kotlin/com/egm/stellio/search/authorization/EntityAccessRightsServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/authorization/SubjectReferentialServiceTests.kt
Labels: feature, authz

#1153 chore: upgrade to Gradle 8.7
  gradle/wrapper/gradle-wrapper.properties
Labels: chore, devops

#1154 feat: add support for `VocabProperty`
  search-service/src/main/kotlin/com/egm/stellio/search/model/EntityTypeInfo.kt
  search-service/src/main/kotlin/com/egm/stellio/search/model/TemporalEntityAttribute.kt
  search-service/src/main/kotlin/com/egm/stellio/search/service/TemporalEntityAttributeService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/util/AttributeInstanceUtils.kt
  search-service/src/main/kotlin/com/egm/stellio/search/util/TemporalEntityBuilder.kt
  search-service/src/main/kotlin/db/migration/V0_29__JsonLd_migration.kt
  search-service/src/test/kotlin/com/egm/stellio/search/service/AttributeInstanceServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/service/EntityTypeServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/support/BusinessObjectsFactory.kt
  search-service/src/test/kotlin/com/egm/stellio/search/support/TestUtils.kt
  search-service/src/test/kotlin/com/egm/stellio/search/util/PatchAttributeTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/util/TemporalEntityParameterizedSource.kt
  search-service/src/test/resources/ngsild/expectations/beehive_vocab_property_temporal_values.jsonld
  search-service/src/test/resources/ngsild/fragments/temporal_instance_vocab_fragment.jsonld
  shared/src/main/kotlin/com/egm/stellio/shared/model/CompactedEntity.kt
  shared/src/main/kotlin/com/egm/stellio/shared/model/NgsiLdEntity.kt
  shared/src/main/kotlin/com/egm/stellio/shared/util/JsonLdUtils.kt
  shared/src/test/kotlin/com/egm/stellio/shared/model/CompactedEntityTests.kt
  shared/src/test/kotlin/com/egm/stellio/shared/model/NgsiLdEntityTests.kt
  shared/src/testFixtures/kotlin/com/egm/stellio/shared/util/JsonLdContextUtils.kt
  shared/src/testFixtures/resources/jsonld-contexts/apic.jsonld
Labels: feature, core, temporal, ngsild-1.7.1

#1151 feat(authz): introduce an owner relationship when creating an entity
  search-service/config/detekt/baseline.xml
  search-service/src/main/kotlin/com/egm/stellio/search/authorization/AuthorizationService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/authorization/DisabledAuthorizationService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/authorization/EnabledAuthorizationService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/authorization/EntityAccessRights.kt
  search-service/src/main/kotlin/com/egm/stellio/search/authorization/EntityAccessRightsService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/web/EntityAccessControlHandler.kt
  search-service/src/main/kotlin/com/egm/stellio/search/web/EntityHandler.kt
  search-service/src/main/kotlin/com/egm/stellio/search/web/EntityOperationHandler.kt
  search-service/src/main/kotlin/com/egm/stellio/search/web/TemporalEntityHandler.kt
  search-service/src/main/resources/db/migration/V0_41__migrate_to_creator_right.sql
  search-service/src/test/kotlin/com/egm/stellio/search/authorization/AuthUtilsTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/authorization/EnabledAuthorizationServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/authorization/EntityAccessRightsServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/web/EntityAccessControlHandlerTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/web/EntityHandlerTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/web/EntityOperationHandlerTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/web/TemporalEntityHandlerTests.kt
  shared/src/main/kotlin/com/egm/stellio/shared/util/ApiResponses.kt
  shared/src/main/kotlin/com/egm/stellio/shared/util/AuthUtils.kt
  shared/src/test/kotlin/com/egm/stellio/shared/util/AuthUtilsTests.kt
  shared/src/testFixtures/resources/jsonld-contexts/authorization.jsonld
  shared/src/testFixtures/resources/ngsild/events/authorization/RightAddOnEntity.json
Labels: feature, authz

#1160 fix: temporal entity queries with lastN parameter and aggregation period duration
  search-service/config/detekt/baseline.xml
  search-service/src/main/kotlin/com/egm/stellio/search/scope/ScopeService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/service/AttributeInstanceService.kt
  search-service/src/test/kotlin/com/egm/stellio/search/scope/ScopeServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/service/AttributeInstanceServiceTests.kt
Labels: fix, temporal
