Repository stellio-hub/stellio-context-broker, pull requests merged in 2024-11, with the labels that each got.

#1256 feat: add support for many EntitySelector objects in Query datatype
  search-service/config/detekt/baseline.xml
  search-service/src/main/kotlin/com/egm/stellio/search/authorization/service/AuthorizationService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/authorization/service/DisabledAuthorizationService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/authorization/service/EnabledAuthorizationService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/authorization/web/EntityAccessControlHandler.kt
  search-service/src/main/kotlin/com/egm/stellio/search/entity/model/EntitiesQuery.kt
  search-service/src/main/kotlin/com/egm/stellio/search/entity/service/EntityQueryService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/entity/util/EntitiesQueryUtils.kt
  search-service/src/main/kotlin/com/egm/stellio/search/entity/web/EntityHandler.kt
  search-service/src/main/kotlin/com/egm/stellio/search/entity/web/EntityOperationHandler.kt
  search-service/src/main/kotlin/com/egm/stellio/search/temporal/model/TemporalEntitiesQuery.kt
  search-service/src/main/kotlin/com/egm/stellio/search/temporal/util/TemporalQueryUtils.kt
  search-service/src/main/kotlin/com/egm/stellio/search/temporal/web/TemporalEntityHandler.kt
  search-service/src/main/kotlin/com/egm/stellio/search/temporal/web/TemporalEntityOperationsHandler.kt
  search-service/src/test/kotlin/com/egm/stellio/search/authorization/service/AuthorizationServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/authorization/service/EnabledAuthorizationServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/entity/service/EntityServiceQueriesTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/entity/util/EntitiesQueryUtilsTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/entity/web/EntityHandlerTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/entity/web/EntityOperationHandlerTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/scope/ScopeServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/scope/TemporalScopeBuilderTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/support/BusinessObjectsFactory.kt
  search-service/src/test/kotlin/com/egm/stellio/search/temporal/service/AggregatedTemporalQueryServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/temporal/service/TemporalPaginationServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/temporal/service/TemporalQueryServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/temporal/util/TemporalEntityBuilderTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/temporal/util/TemporalQueryUtilsTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/temporal/web/TemporalEntityHandlerTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/temporal/web/TemporalEntityOperationsHandlerTests.kt
Labels: feature, core, temporal

#1232 CSR Implementation
  .context-source.env
  .env
  api-gateway/src/main/kotlin/com/egm/stellio/apigateway/ApiGatewayApplication.kt
  docker-compose.yml
  search-service/build.gradle.kts
  search-service/config/detekt/baseline.xml
  search-service/src/main/kotlin/com/egm/stellio/search/common/model/Query.kt
  search-service/src/main/kotlin/com/egm/stellio/search/csr/model/CSRFilters.kt
  search-service/src/main/kotlin/com/egm/stellio/search/csr/model/ContextSourceRegistration.kt
  search-service/src/main/kotlin/com/egm/stellio/search/csr/model/Mode.kt
  search-service/src/main/kotlin/com/egm/stellio/search/csr/model/NGSILDWarning.kt
  search-service/src/main/kotlin/com/egm/stellio/search/csr/model/Operation.kt
  search-service/src/main/kotlin/com/egm/stellio/search/csr/service/ContextSourceCaller.kt
  search-service/src/main/kotlin/com/egm/stellio/search/csr/service/ContextSourceRegistrationService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/csr/service/ContextSourceUtils.kt
  search-service/src/main/kotlin/com/egm/stellio/search/csr/web/ContextSourceRegistrationHandler.kt
  search-service/src/main/kotlin/com/egm/stellio/search/entity/web/EntityHandler.kt
  search-service/src/main/resources/db/migration/V0_43__add_csr.sql
  search-service/src/test/kotlin/com/egm/stellio/search/authorization/web/AnonymousUserHandlerTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/csr/CsrUtils.kt
  search-service/src/test/kotlin/com/egm/stellio/search/csr/model/ContextSourceRegistrationTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/csr/service/ContextSourceCallerTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/csr/service/ContextSourceRegistrationServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/csr/service/ContextSourceUtilsTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/csr/web/ContextSourceRegistrationHandlerTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/entity/web/EntityHandlerTests.kt
  search-service/src/test/resources/ngsild/csr/contextSourceRegistration.jsonld
  search-service/src/test/resources/ngsild/csr/contextSourceRegistration_full.json
  search-service/src/test/resources/ngsild/csr/contextSourceRegistration_minimal_entities.json
  shared/src/main/kotlin/com/egm/stellio/shared/model/CompactedEntity.kt
  shared/src/main/kotlin/com/egm/stellio/shared/util/ApiResponses.kt
  shared/src/main/kotlin/com/egm/stellio/shared/util/DataTypes.kt
  shared/src/main/kotlin/com/egm/stellio/shared/util/JsonLdUtils.kt
  shared/src/main/kotlin/com/egm/stellio/shared/util/JsonUtils.kt
  shared/src/test/kotlin/com/egm/stellio/shared/util/JsonUtilsTests.kt
  shared/src/test/kotlin/com/egm/stellio/shared/web/ExceptionHandlerTests.kt
  subscription-service/src/main/kotlin/com/egm/stellio/subscription/service/SubscriptionService.kt
Labels: feature

#1265 fix: return InvalidRequest for invalidPayload
  shared/src/main/kotlin/com/egm/stellio/shared/util/JsonUtils.kt
  shared/src/test/kotlin/com/egm/stellio/shared/util/JsonUtilsTests.kt
  shared/src/test/kotlin/com/egm/stellio/shared/web/ExceptionHandlerTests.kt
Labels: feature

#1267 fix: createdAt format to ngsiLd DateTime
  search-service/src/main/kotlin/com/egm/stellio/search/entity/service/EntityService.kt
Labels: fix

#1264 feat(common): simplify internal error handling
  search-service/src/main/kotlin/com/egm/stellio/search/authorization/web/EntityAccessControlHandler.kt
  search-service/src/main/kotlin/com/egm/stellio/search/csr/web/ContextSourceRegistrationHandler.kt
  search-service/src/main/kotlin/com/egm/stellio/search/discovery/web/AttributeHandler.kt
  search-service/src/main/kotlin/com/egm/stellio/search/discovery/web/EntityTypeHandler.kt
  search-service/src/main/kotlin/com/egm/stellio/search/entity/web/EntityHandler.kt
  search-service/src/main/kotlin/com/egm/stellio/search/entity/web/EntityOperationHandler.kt
  search-service/src/main/kotlin/com/egm/stellio/search/temporal/web/TemporalEntityHandler.kt
  search-service/src/main/kotlin/com/egm/stellio/search/temporal/web/TemporalEntityOperationsHandler.kt
  search-service/src/test/kotlin/com/egm/stellio/search/authorization/web/EntityAccessControlHandlerTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/discovery/web/AttributeHandlerTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/discovery/web/EntityTypeHandlerTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/entity/web/EntityHandlerTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/entity/web/EntityOperationHandlerTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/temporal/web/TemporalEntityHandlerTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/temporal/web/TemporalEntityOperationsHandlerTests.kt
  shared/src/main/kotlin/com/egm/stellio/shared/model/ApiExceptions.kt
  shared/src/main/kotlin/com/egm/stellio/shared/model/ErrorResponse.kt
  shared/src/main/kotlin/com/egm/stellio/shared/util/ApiResponses.kt
  shared/src/main/kotlin/com/egm/stellio/shared/web/ExceptionHandler.kt
  shared/src/main/kotlin/com/egm/stellio/shared/web/TenantWebFilter.kt
  shared/src/test/kotlin/com/egm/stellio/shared/web/TenantWebFilterTests.kt
  subscription-service/src/main/kotlin/com/egm/stellio/subscription/web/SubscriptionHandler.kt
  subscription-service/src/test/kotlin/com/egm/stellio/subscription/web/SubscriptionHandlerTests.kt
Labels: feature

#1261 feat(core): Linked Entity Retrieval - Part 1
  search-service/config/detekt/baseline.xml
  search-service/src/main/kotlin/com/egm/stellio/search/common/model/Query.kt
  search-service/src/main/kotlin/com/egm/stellio/search/entity/model/EntitiesQuery.kt
  search-service/src/main/kotlin/com/egm/stellio/search/entity/service/LinkedEntityService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/entity/util/EntitiesQueryUtils.kt
  search-service/src/main/kotlin/com/egm/stellio/search/entity/web/EntityHandler.kt
  search-service/src/test/kotlin/com/egm/stellio/search/authorization/web/AnonymousUserHandlerTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/entity/service/LinkedEntityServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/entity/util/EntitiesQueryUtilsTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/entity/web/EntityHandlerTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/support/BusinessObjectsFactory.kt
  shared/config/detekt/baseline.xml
  shared/src/main/kotlin/com/egm/stellio/shared/model/CompactedEntity.kt
  shared/src/main/kotlin/com/egm/stellio/shared/model/LinkedEntityQuery.kt
  shared/src/main/kotlin/com/egm/stellio/shared/util/ApiUtils.kt
  shared/src/main/kotlin/com/egm/stellio/shared/util/JsonLdUtils.kt
  shared/src/main/kotlin/com/egm/stellio/shared/util/LinkedEntityQueryUtils.kt
  shared/src/test/kotlin/com/egm/stellio/shared/model/CompactedEntityFixtureData.kt
  shared/src/test/kotlin/com/egm/stellio/shared/model/CompactedEntityLinkedTests.kt
  shared/src/test/kotlin/com/egm/stellio/shared/model/CompactedEntityTests.kt
  shared/src/testFixtures/kotlin/com/egm/stellio/shared/util/JsonLdContextUtils.kt
  shared/src/testFixtures/kotlin/com/egm/stellio/shared/util/TestUtils.kt
  subscription-service/config/detekt/baseline.xml
  subscription-service/src/main/kotlin/com/egm/stellio/subscription/service/SubscriptionService.kt
Labels: feature, core
