Repository stellio-hub/stellio-context-broker, pull requests merged in 2025-03, with the labels that each got.

#1348 fix(core): do not query for linked entities if no relationships in input entities
  search-service/src/main/kotlin/com/egm/stellio/search/entity/service/LinkedEntityService.kt
  search-service/src/test/kotlin/com/egm/stellio/search/entity/service/LinkedEntityServiceTests.kt
Labels: fix, core

#1352 fix(devops): misc changes in Dockerfiles to fix Anchore warnings
  api-gateway/Dockerfile
  search-service/Dockerfile
  subscription-service/Dockerfile
Labels: fix, devops

#1355 chore: clean and automatically check unnecessary stubs
  build.gradle.kts
  search-service/src/test/kotlin/com/egm/stellio/search/authorization/service/EntityAccessRightsServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/authorization/web/EntityAccessControlHandlerTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/entity/service/EntityOperationServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/entity/service/EntityServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/entity/service/LinkedEntityServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/entity/web/EntityOperationHandlerTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/temporal/util/TemporalQueryUtilsTests.kt
  subscription-service/src/test/kotlin/com/egm/stellio/subscription/web/SubscriptionHandlerTests.kt
Labels: chore

#1354 fix(core): handle previously deleted attributes when appending or updating an attribute
  search-service/src/main/kotlin/com/egm/stellio/search/entity/service/EntityAttributeService.kt
  search-service/src/test/kotlin/com/egm/stellio/search/entity/service/EntityAttributeServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/temporal/service/AggregatedTemporalQueryServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/temporal/service/AttributeInstanceServiceTests.kt
Labels: fix, core

#1364 fix: escape single quotes in the input entity matched with the subscription
  shared/src/main/kotlin/com/egm/stellio/shared/util/QueryUtils.kt
  subscription-service/src/test/kotlin/com/egm/stellio/subscription/service/SubscriptionServiceTests.kt
  subscription-service/src/test/resources/ngsild/beehive_single_quote.jsonld
Labels: fix, subscription

#1365 fix(temporal): allow retrieving temporal evolution of an entity when deleted from the current state
  search-service/src/main/kotlin/com/egm/stellio/search/entity/service/EntityAttributeService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/entity/service/EntityQueryService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/entity/service/EntityService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/temporal/service/TemporalQueryService.kt
  search-service/src/test/kotlin/com/egm/stellio/search/entity/service/EntityServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/temporal/service/TemporalQueryServiceTests.kt
Labels: fix, temporal

#1349 Feature/distribute replace
  search-service/config/detekt/baseline.xml
  search-service/src/main/kotlin/com/egm/stellio/search/csr/model/ContextSourceRegistration.kt
  search-service/src/main/kotlin/com/egm/stellio/search/csr/model/Operation.kt
  search-service/src/main/kotlin/com/egm/stellio/search/csr/model/RegistrationInfoFilter.kt
  search-service/src/main/kotlin/com/egm/stellio/search/csr/service/DistributedEntityProvisionService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/entity/web/BatchAPIResponses.kt
  search-service/src/main/kotlin/com/egm/stellio/search/entity/web/EntityHandler.kt
  search-service/src/test/kotlin/com/egm/stellio/search/csr/model/ContextSourceRegistrationTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/csr/service/DistributedEntityProvisionServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/entity/web/EntityHandlerTests.kt
  shared/src/main/kotlin/com/egm/stellio/shared/model/EntitySelector.kt
  shared/src/main/kotlin/com/egm/stellio/shared/model/ExpandedEntity.kt
  shared/src/test/kotlin/com/egm/stellio/shared/model/EntityTypeSelectorTests.kt
Labels: feature, csr

#1350 Feature/modifiedAt at creation
  search-service/src/main/kotlin/com/egm/stellio/search/csr/model/ContextSourceRegistration.kt
  search-service/src/main/kotlin/com/egm/stellio/search/csr/service/ContextSourceRegistrationService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/entity/model/Attribute.kt
  search-service/src/main/kotlin/com/egm/stellio/search/entity/model/Entity.kt
  search-service/src/main/kotlin/com/egm/stellio/search/entity/service/EntityAttributeService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/entity/service/EntityService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/entity/util/EntityUtils.kt
  search-service/src/main/kotlin/com/egm/stellio/search/temporal/model/AttributeInstance.kt
  search-service/src/main/resources/db/migration/V0_46_make_modified_at_not_nullable.sql
  search-service/src/test/kotlin/com/egm/stellio/search/entity/service/EntityAttributeServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/entity/service/EntityQueryServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/entity/service/EntityServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/temporal/service/TemporalQueryServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/temporal/util/TemporalEntityBuilderTests.kt
  search-service/src/test/resources/ngsild/beehive_expanded.jsonld
  search-service/src/test/resources/ngsild/beehive_two_temporal_properties.jsonld
  search-service/src/test/resources/ngsild/expectations/beehive_aggregated_outgoing.jsonld
  shared/src/main/kotlin/com/egm/stellio/shared/model/ExpandedEntity.kt
  subscription-service/config/detekt/baseline.xml
  subscription-service/src/main/kotlin/com/egm/stellio/subscription/model/Subscription.kt
  subscription-service/src/main/kotlin/com/egm/stellio/subscription/service/SubscriptionService.kt
  subscription-service/src/test/kotlin/com/egm/stellio/subscription/service/SubscriptionServiceTests.kt
  subscription-service/src/test/kotlin/com/egm/stellio/subscription/support/FixtureUtils.kt
  subscription-service/src/test/kotlin/com/egm/stellio/subscription/web/SubscriptionHandlerTests.kt
Labels: feature, core

#1369 refactor: align internal event naming and topology with notification triggers
  search-service/config/detekt/baseline.xml
  search-service/src/main/kotlin/com/egm/stellio/search/authorization/listener/IAMListener.kt
  search-service/src/main/kotlin/com/egm/stellio/search/authorization/web/EntityAccessControlHandler.kt
  search-service/src/main/kotlin/com/egm/stellio/search/entity/model/UpdateResult.kt
  search-service/src/main/kotlin/com/egm/stellio/search/entity/service/EntityAttributeService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/entity/service/EntityEventService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/entity/service/EntityService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/scope/ScopeService.kt
  search-service/src/test/kotlin/com/egm/stellio/search/entity/model/UpdateResultTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/entity/service/EntityAttributeServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/entity/service/EntityEventServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/entity/service/EntityServiceTests.kt
  shared/src/main/kotlin/com/egm/stellio/shared/model/EntityEvent.kt
  shared/src/test/kotlin/com/egm/stellio/shared/util/JsonUtilsTests.kt
  shared/src/testFixtures/resources/ngsild/events/authorization/ClientIdAppendToClient.json
  shared/src/testFixtures/resources/ngsild/events/authorization/GroupMembershipAppendEvent.json
  shared/src/testFixtures/resources/ngsild/events/authorization/GroupUpdateEvent.json
  shared/src/testFixtures/resources/ngsild/events/authorization/RealmRoleAppendEventNoRole.json
  shared/src/testFixtures/resources/ngsild/events/authorization/RealmRoleAppendEventOneRole.json
  shared/src/testFixtures/resources/ngsild/events/authorization/RealmRoleAppendEventTwoRoles.json
  shared/src/testFixtures/resources/ngsild/events/authorization/RealmRoleAppendToClient.json
  shared/src/testFixtures/resources/ngsild/events/authorization/RightAddOnEntity.json
  shared/src/testFixtures/resources/ngsild/events/authorization/RightRemoveOnEntity.json
  shared/src/testFixtures/resources/ngsild/events/authorization/SpecificAccessPolicyAddOnEntity.json
  shared/src/testFixtures/resources/ngsild/events/authorization/UserUpdateEvent.json
  shared/src/testFixtures/resources/ngsild/events/entity/attributeAppendNumericPropDatasetIdEvent.json
  shared/src/testFixtures/resources/ngsild/events/entity/attributeAppendNumericPropEvent.json
  shared/src/testFixtures/resources/ngsild/events/entity/attributeAppendRelEvent.json
  shared/src/testFixtures/resources/ngsild/events/entity/attributeAppendTextPropEvent.json
  shared/src/testFixtures/resources/ngsild/events/entity/attributeAppendTypeEvent.json
  shared/src/testFixtures/resources/ngsild/events/entity/attributeReplaceNumericPropEvent.json
  shared/src/testFixtures/resources/ngsild/events/entity/attributeReplaceRelEvent.json
  shared/src/testFixtures/resources/ngsild/events/entity/attributeReplaceTextPropEvent.json
  shared/src/testFixtures/resources/ngsild/events/entity/invalid/humidityAppendEvent.jsonld
  subscription-service/config/detekt/baseline.xml
  subscription-service/src/main/kotlin/com/egm/stellio/subscription/listener/EntityEventListenerService.kt
  subscription-service/src/test/kotlin/com/egm/stellio/subscription/listener/EntityEventListenerServiceTests.kt
Labels: refactoring, core, subscription
