Repository stellio-hub/stellio-context-broker, pull requests merged in 2025-04, with the labels that each got.

#1351 feat(csr): implement minimal filters for distributed consumption operations
  search-service/src/main/kotlin/com/egm/stellio/search/csr/model/CSRFilters.kt
  search-service/src/main/kotlin/com/egm/stellio/search/csr/model/ContextSourceRegistration.kt
  search-service/src/main/kotlin/com/egm/stellio/search/csr/service/ContextSourceRegistrationService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/csr/service/DistributedEntityConsumptionService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/csr/service/DistributedEntityProvisionService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/csr/web/ContextSourceRegistrationHandler.kt
  search-service/src/main/kotlin/com/egm/stellio/search/entity/web/EntityHandler.kt
  search-service/src/test/kotlin/com/egm/stellio/search/csr/CsrUtils.kt
  search-service/src/test/kotlin/com/egm/stellio/search/csr/model/ContextSourceRegistrationTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/csr/service/ContextSourceRegistrationServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/csr/service/DistributedEntityConsumptionServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/csr/service/DistributedEntityProvisionServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/entity/web/EntityHandlerTests.kt
  shared/src/main/kotlin/com/egm/stellio/shared/model/ExpandedEntity.kt
  shared/src/main/kotlin/com/egm/stellio/shared/util/QueryUtils.kt
Labels: feature, csr

#1381 fix: entity payload wrongly updated after updating a type
  search-service/src/main/kotlin/com/egm/stellio/search/entity/service/EntityService.kt
Labels: fix, core

#1371 feat: align API operations with notification triggers
  search-service/config/detekt/baseline.xml
  search-service/src/main/kotlin/com/egm/stellio/search/authorization/listener/IAMListener.kt
  search-service/src/main/kotlin/com/egm/stellio/search/entity/model/Entity.kt
  search-service/src/main/kotlin/com/egm/stellio/search/entity/model/UpdateResult.kt
  search-service/src/main/kotlin/com/egm/stellio/search/entity/service/EntityAttributeService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/entity/service/EntityEventService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/entity/service/EntityQueryService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/entity/service/EntityService.kt
  search-service/src/test/kotlin/com/egm/stellio/search/entity/model/UpdateResultTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/entity/service/EntityAttributeServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/entity/service/EntityEventServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/entity/service/EntityOperationServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/entity/service/EntityServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/entity/web/EntityHandlerTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/support/BusinessObjectsFactory.kt
  search-service/src/test/resources/ngsild/beehive_for_replacement.jsonld
  search-service/src/test/resources/ngsild/beehive_replacement.jsonld
  shared/src/main/kotlin/com/egm/stellio/shared/model/EntityEvent.kt
  shared/src/main/kotlin/com/egm/stellio/shared/model/ExpandedMembers.kt
  shared/src/main/kotlin/com/egm/stellio/shared/util/JsonLdUtils.kt
  shared/src/test/kotlin/com/egm/stellio/shared/util/JsonUtilsTests.kt
  shared/src/testFixtures/resources/ngsild/events/entity/entityReplaceEvent.json
  subscription-service/src/main/kotlin/com/egm/stellio/subscription/listener/EntityEventListenerService.kt
  subscription-service/src/test/kotlin/com/egm/stellio/subscription/listener/EntityEventListenerServiceTests.kt
Labels: feature

#1382 fix(core): context is at the same level than the `Feature` in GeoJson representation
  shared/src/main/kotlin/com/egm/stellio/shared/model/CompactedEntity.kt
  shared/src/test/kotlin/com/egm/stellio/shared/model/CompactedEntityTests.kt
Labels: fix, core

#1383 fix(batch): expected responses in invalid batch operations
  search-service/src/main/kotlin/com/egm/stellio/search/entity/web/EntityOperationHandler.kt
  search-service/src/test/kotlin/com/egm/stellio/search/entity/web/EntityOperationHandlerTests.kt
  shared/src/main/kotlin/com/egm/stellio/shared/util/ApiUtils.kt
  shared/src/main/kotlin/com/egm/stellio/shared/util/DataRepresentationUtils.kt
  shared/src/main/kotlin/com/egm/stellio/shared/util/JsonLdUtils.kt
  shared/src/test/kotlin/com/egm/stellio/shared/util/ApiUtilsTests.kt
  shared/src/test/kotlin/com/egm/stellio/shared/util/JsonLdUtilsTests.kt
Labels: fix, core
