Repository stellio-hub/stellio-context-broker, pull requests merged in 2025-07, with the labels that each got.

#1419 feat: check validity of endpoint URI
  subscription-service/src/main/kotlin/com/egm/stellio/subscription/model/Endpoint.kt
  subscription-service/src/main/kotlin/com/egm/stellio/subscription/model/Subscription.kt
  subscription-service/src/main/kotlin/com/egm/stellio/subscription/service/NotificationService.kt
  subscription-service/src/main/kotlin/com/egm/stellio/subscription/service/SubscriptionService.kt
  subscription-service/src/main/kotlin/com/egm/stellio/subscription/service/mqtt/Mqtt.kt
  subscription-service/src/main/kotlin/com/egm/stellio/subscription/service/mqtt/MqttNotificationService.kt
  subscription-service/src/test/kotlin/com/egm/stellio/subscription/model/SubscriptionTests.kt
  subscription-service/src/test/kotlin/com/egm/stellio/subscription/support/WithMosquittoContainer.kt
Labels: feature, subscription

#1420 refactor: retrieve sub from SecurityContext instead of passing it as a parameter everywhere
  search-service/config/detekt/baseline.xml
  search-service/src/main/kotlin/com/egm/stellio/search/authorization/listener/IAMListener.kt
  search-service/src/main/kotlin/com/egm/stellio/search/authorization/service/AuthorizationService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/authorization/service/DisabledAuthorizationService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/authorization/service/EnabledAuthorizationService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/authorization/service/EntityAccessRightsService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/authorization/service/SubjectReferentialService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/authorization/web/EntityAccessControlHandler.kt
  search-service/src/main/kotlin/com/egm/stellio/search/entity/service/EntityAttributeService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/entity/service/EntityOperationService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/entity/service/EntityQueryService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/entity/service/EntityService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/entity/service/LinkedEntityService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/entity/web/EntityHandler.kt
  search-service/src/main/kotlin/com/egm/stellio/search/entity/web/EntityOperationHandler.kt
  search-service/src/main/kotlin/com/egm/stellio/search/scope/ScopeService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/temporal/service/TemporalQueryService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/temporal/service/TemporalService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/temporal/web/TemporalEntityHandler.kt
  search-service/src/main/kotlin/com/egm/stellio/search/temporal/web/TemporalEntityOperationsHandler.kt
  search-service/src/test/kotlin/com/egm/stellio/search/authorization/SubjectInfoUtils.kt
  search-service/src/test/kotlin/com/egm/stellio/search/authorization/listener/IAMListenerTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/authorization/service/AuthorizationServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/authorization/service/EnabledAuthorizationServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/authorization/service/EntityAccessRightsServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/authorization/service/SubjectReferentialServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/authorization/web/EntityAccessControlHandlerTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/entity/service/EntityAttributeServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/entity/service/EntityOperationServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/entity/service/EntityQueryServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/entity/service/EntityServiceQueriesTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/entity/service/EntityServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/entity/service/LinkedEntityServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/entity/web/EntityHandlerTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/entity/web/EntityOperationHandlerTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/temporal/service/TemporalQueryServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/temporal/service/TemporalServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/temporal/web/TemporalEntityHandlerPaginationTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/temporal/web/TemporalEntityHandlerTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/temporal/web/TemporalEntityOperationsHandlerTests.kt
  shared/src/main/kotlin/com/egm/stellio/shared/util/AuthUtils.kt
Labels: refactoring, core

#1425 fix: add subject type in permission details
  search-service/config/detekt/baseline.xml
  search-service/src/main/kotlin/com/egm/stellio/search/authorization/permission/service/EnabledAuthorizationService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/authorization/permission/service/PermissionService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/authorization/permission/web/PermissionHandler.kt
  search-service/src/main/kotlin/com/egm/stellio/search/authorization/subject/model/SubjectReferential.kt
  search-service/src/main/kotlin/com/egm/stellio/search/authorization/subject/service/SubjectReferentialService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/csr/service/ContextSourceRegistrationService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/csr/web/ContextSourceRegistrationHandler.kt
  search-service/src/main/kotlin/com/egm/stellio/search/entity/service/EntityAttributeService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/entity/service/EntityService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/scope/ScopeService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/temporal/service/AttributeInstanceService.kt
  search-service/src/test/kotlin/com/egm/stellio/search/authorization/permission/web/PermissionHandlerTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/csr/service/ContextSourceRegistrationServiceTests.kt
  shared/src/main/kotlin/com/egm/stellio/shared/util/AuthUtils.kt
  shared/src/testFixtures/kotlin/com/egm/stellio/shared/util/TestUtils.kt
  subscription-service/config/detekt/baseline.xml
  subscription-service/src/main/kotlin/com/egm/stellio/subscription/service/SubscriptionService.kt
  subscription-service/src/main/kotlin/com/egm/stellio/subscription/web/SubscriptionHandler.kt
  subscription-service/src/test/kotlin/com/egm/stellio/subscription/service/SubscriptionServiceTests.kt
  subscription-service/src/test/kotlin/com/egm/stellio/subscription/web/SubscriptionHandlerTests.kt
Labels: fix

#1428 feat: extract dependencies into a specific docker compose file
  docker-compose-dependencies.yml
  docker-compose.yml
Labels: feature

#1429 fix: incorrect structure of logback configuration files
  api-gateway/src/main/resources/logback-spring.xml
  search-service/src/main/resources/logback-spring.xml
  subscription-service/src/main/resources/logback-spring.xml
Labels: fix
