Repository stellio-hub/stellio-context-broker, pull requests merged in 2025-01, with the labels that each got.

#1301 chore: upgrade to Timescale 2.17.2
  docker-compose.yml
  search-service/docker-compose.yml
  search-service/src/test/kotlin/com/egm/stellio/search/support/WithTimescaleContainer.kt
  subscription-service/docker-compose.yml
  subscription-service/src/test/kotlin/com/egm/stellio/subscription/support/WithTimescaleContainer.kt
Labels: chore, devops

#1305 fix: incorrect order of parameters when calling PostGIS functions
  search-service/src/test/kotlin/com/egm/stellio/search/entity/service/EntityServiceQueriesTests.kt
  shared/src/main/kotlin/com/egm/stellio/shared/queryparameter/GeoQuery.kt
  shared/src/test/kotlin/com/egm/stellio/shared/util/GeoQueryUtilsTests.kt
  subscription-service/src/test/kotlin/com/egm/stellio/subscription/service/SubscriptionServiceTests.kt
Labels: fix

#1307 fix: ensure to have correct attribute id when a previous one existed
  search-service/src/main/kotlin/com/egm/stellio/search/entity/service/EntityAttributeService.kt
Labels: fix

#1310 fix: do a partial update patch in update attributes (and not a replace)
  search-service/config/detekt/baseline.xml
  search-service/src/main/kotlin/com/egm/stellio/search/entity/service/EntityAttributeService.kt
Labels: fix, core

#1299 feat: add support for the format parameter
  search-service/config/detekt/baseline.xml
  search-service/src/main/kotlin/com/egm/stellio/search/authorization/web/EntityAccessControlHandler.kt
  search-service/src/main/kotlin/com/egm/stellio/search/entity/web/EntityHandler.kt
  search-service/src/main/kotlin/com/egm/stellio/search/entity/web/EntityOperationHandler.kt
  search-service/src/main/kotlin/com/egm/stellio/search/scope/ScopeService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/scope/TemporalScopeBuilder.kt
  search-service/src/main/kotlin/com/egm/stellio/search/temporal/model/TemporalEntitiesQuery.kt
  search-service/src/main/kotlin/com/egm/stellio/search/temporal/service/AttributeInstanceService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/temporal/service/TemporalPaginationService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/temporal/service/TemporalQueryService.kt
  search-service/src/main/kotlin/com/egm/stellio/search/temporal/util/TemporalEntityBuilder.kt
  search-service/src/main/kotlin/com/egm/stellio/search/temporal/util/TemporalQueryUtils.kt
  search-service/src/main/kotlin/com/egm/stellio/search/temporal/web/TemporalApiResponses.kt
  search-service/src/main/kotlin/com/egm/stellio/search/temporal/web/TemporalEntityHandler.kt
  search-service/src/test/kotlin/com/egm/stellio/search/entity/util/EntitiesQueryUtilsTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/entity/web/EntityHandlerTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/scope/ScopeServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/scope/TemporalScopeBuilderTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/support/BusinessObjectsFactory.kt
  search-service/src/test/kotlin/com/egm/stellio/search/temporal/service/AggregatedTemporalQueryServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/temporal/service/AttributeInstanceServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/temporal/service/TemporalPaginationServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/temporal/service/TemporalQueryServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/temporal/util/TemporalEntitiesParameterizedSource.kt
  search-service/src/test/kotlin/com/egm/stellio/search/temporal/util/TemporalEntityBuilderTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/temporal/util/TemporalEntityParameterizedSource.kt
  search-service/src/test/kotlin/com/egm/stellio/search/temporal/util/TemporalQueryUtilsTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/temporal/web/TemporalEntityHandlerTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/temporal/web/TemporalEntityOperationsHandlerTests.kt
  shared/src/main/kotlin/com/egm/stellio/shared/model/NgsiLdDataRepresentation.kt
  shared/src/main/kotlin/com/egm/stellio/shared/queryparameter/FormatValue.kt
  shared/src/main/kotlin/com/egm/stellio/shared/queryparameter/OptionsValue.kt
  shared/src/main/kotlin/com/egm/stellio/shared/queryparameter/QueryParameter.kt
  shared/src/main/kotlin/com/egm/stellio/shared/util/ApiUtils.kt
  shared/src/test/kotlin/com/egm/stellio/shared/model/NgsiLdDataRepresentationTests.kt
  shared/src/test/kotlin/com/egm/stellio/shared/util/ApiUtilsTests.kt
Labels: feature, common, ngsild-1.8.1

#1317 refactor: parse representations in entity handlers
  search-service/src/main/kotlin/com/egm/stellio/search/authorization/web/EntityAccessControlHandler.kt
  search-service/src/main/kotlin/com/egm/stellio/search/entity/web/EntityHandler.kt
  search-service/src/main/kotlin/com/egm/stellio/search/entity/web/EntityOperationHandler.kt
Labels: refactoring

#1320 chore: remove now unused ObservationListener
  search-service/src/main/kotlin/com/egm/stellio/search/entity/listener/ObservationEventListener.kt
  search-service/src/main/kotlin/com/egm/stellio/search/entity/service/EntityEventService.kt
  search-service/src/test/kotlin/com/egm/stellio/search/entity/listener/ObservationEventListenerTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/entity/service/EntityEventServiceTests.kt
  shared/src/main/kotlin/com/egm/stellio/shared/model/EntityEvent.kt
  shared/src/test/kotlin/com/egm/stellio/shared/util/JsonUtilsTests.kt
  shared/src/testFixtures/resources/ngsild/events/entity/attributeAppendNumericPropDatasetIdEvent.json
  shared/src/testFixtures/resources/ngsild/events/entity/attributeAppendNumericPropEvent.json
  shared/src/testFixtures/resources/ngsild/events/entity/attributeAppendRelEvent.json
  shared/src/testFixtures/resources/ngsild/events/entity/attributeAppendTextPropEvent.json
  shared/src/testFixtures/resources/ngsild/events/entity/attributeAppendTypeEvent.json
  shared/src/testFixtures/resources/ngsild/events/entity/attributeDeleteEvent.json
  shared/src/testFixtures/resources/ngsild/events/entity/attributeReplaceNumericPropEvent.json
  shared/src/testFixtures/resources/ngsild/events/entity/attributeReplaceRelEvent.json
  shared/src/testFixtures/resources/ngsild/events/entity/attributeReplaceTextPropEvent.json
  shared/src/testFixtures/resources/ngsild/events/entity/attributeUpdateNumericPropDatasetIdEvent.json
  shared/src/testFixtures/resources/ngsild/events/entity/attributeUpdateNumericPropEvent.json
  shared/src/testFixtures/resources/ngsild/events/entity/attributeUpdateRelEvent.json
  shared/src/testFixtures/resources/ngsild/events/entity/attributeUpdateTextPropEvent.json
  shared/src/testFixtures/resources/ngsild/events/entity/entityCreateEvent.json
  shared/src/testFixtures/resources/ngsild/events/entity/entityDeleteEvent.json
  shared/src/testFixtures/resources/ngsild/events/entity/entityReplaceEvent.json
Labels: chore

#1319 feat: add support for user defined geo properties
  search-service/src/test/kotlin/com/egm/stellio/search/entity/service/EntityQueryServiceTests.kt
  search-service/src/test/kotlin/com/egm/stellio/search/entity/service/EntityServiceTests.kt
  shared/src/main/kotlin/com/egm/stellio/shared/util/JsonLdUtils.kt
  shared/src/test/kotlin/com/egm/stellio/shared/util/JsonLdUtilsTests.kt
Labels: feature, core

#1316 refactor: filterAttributes return type
  search-service/src/main/kotlin/com/egm/stellio/search/entity/web/EntityHandler.kt
  shared/src/main/kotlin/com/egm/stellio/shared/model/ExpandedEntity.kt
  shared/src/main/kotlin/com/egm/stellio/shared/util/JsonLdUtils.kt
  shared/src/test/kotlin/com/egm/stellio/shared/model/ExpandedEntityTests.kt
  subscription-service/src/main/kotlin/com/egm/stellio/subscription/service/NotificationService.kt
Labels: refactoring
